In [1]:
"""
https://www.udemy.com/course/python-programlama-dili-sifirdan-veri-bilimi-icin-giris/learn/lecture/24646138?start=0#overview
2 saat

online python için

https://www.python.org/shell/
https://trinket.io/python3
https://www.onlinegdb.com/online_python_interpreter

conda list

pip install tensorflow

Findall ile email filtreleme:

"""

'\nhttps://www.udemy.com/course/python-programlama-dili-sifirdan-veri-bilimi-icin-giris/learn/lecture/24646138?start=0#overview\n2 saat\n\nonline python için\n\nhttps://www.python.org/shell/\nhttps://trinket.io/python3\nhttps://www.onlinegdb.com/online_python_interpreter\n\nconda list\n\npip install tensorflow\n\nFindall ile email filtreleme:\n\n'

In [3]:
#Metinden Mail Adresini çıkarma
#re regular expression

In [1]:
import re

In [2]:
data = open('data.txt')
oku=data.read()
print(oku)

 Python is a great object-oriented, interpreted, and interactive programming language. It is often compared (favorably of course :-) ) to Lisp, Tcl, Perl, Ruby, C#, Visual Basic, Visual Fox Pro, Scheme or Java... and it's much more fun. jamuir@yahoo.com Welcome to the Python Wiki, a user-editable compendium of knowledge based around the Python programming language. Some pages are protected against casual editing - see WikiEditingGuidelines for more information about editing content.

Python is a great object-oriented, interpreted, and interactive programming language. It is often compared (favorably of course :-) ) to Lisp, Tcl, Perl, Ruby, C#, Visual Basic, Visual Fox Pro, Scheme or Java... and it's much more fun.

Python combines remarkable power with very clear syntax. It has modules, classes, exceptions, very high level dynamic data types, and dynamic typing. There are interfaces to many system calls and libraries, as well as to various windowing systems. New built-in modules are e

In [3]:
mail_listesi=re.findall("\S+@\S+",oku)
print(mail_listesi)
#S ler spaceten geliyor. 2 tane boşluk olacak merkezinde 
#de @ olacak başında sonunda birer boşluk
#tüm metin oku değişkeni içinde yer alıyor

['jamuir@yahoo.com', 'miyop@msn.com', 'absrtfffffaa@comcast.net', 'jshirley@mac.com', 'seebs@optonline.net', 'cgcra@mac.com', 'fukuchi@icloud.com', 'arathi@mac.com', 'godeke@yahoo.com', 'drhyde@comcast.net', 'denism@hotmail.com', 'phish@optonline.net']


In [4]:
#bir metinde yapılan harcamaları filtrelemek

In [5]:
import re
x="2020 yılında ortalama fiyat $20000 olurken 2021'de $25000'a yükselir"
y=re.findall("\$[0-9.]+",x)
print(y)
# $ ile başlayan 0dan9a sayıları al

['$20000', '$25000']


In [6]:
#re kutuphanesi ve findall

In [7]:
import re

In [10]:
x="Bu resimde 5 farklı rengin 39 farklı tonu 12 defa tekrarlanmıştır."

In [11]:
y=re.findall("[0-9]+",x)  #x ifadesini kullan diyoruz. bu x ifadesinde 0 ile
#9 arasındaki rakamları çek diyoruz
print(y)

['5', '39', '12']


In [12]:
y[0]

'5'

In [ ]:
"""
numpay vektör ve matrisleri kullanır
yatay ve düşey eksende kopyalayabilir ve birleştirebilir
[1,2,3]  liste
([1,2,3])  array(Dizi)  liste dışına () ile Dizi elde ediyoruz
([1,2,3],[4,5,6])  tuple (demet ya da dizin)
{'bir':1,'iki':2}  dict(Sözlük)
"""

In [14]:
import numpy as np
liste=[1,2,3]
dizi=np.array(liste)
dizi

array([1, 2, 3])

In [16]:
liste2=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16]
a=np.array(liste2)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [17]:
a=a.reshape(4,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [18]:
import pandas as pd
tablo=pd.DataFrame(a)
tablo

0   1   2   3
0   1   2   3   4
1   5   6   7   8
2   9  10  11  12
3  13  14  15  16

In [19]:
tablo=pd.DataFrame(a,index=["A","B","C","D"],columns=["X","Y","Z","T"])
tablo

X   Y   Z   T
A   1   2   3   4
B   5   6   7   8
C   9  10  11  12
D  13  14  15  16

In [20]:
tablo.to_excel("Tablo1.xlsx")

In [21]:
liste=[]
type(liste)

list

In [22]:
liste=[1,2,3]
liste

[1, 2, 3]

In [23]:
liste+=1
liste #iterable olmadığı hatasını fırlatır

TypeError: 'int' object is not iterable

In [24]:
import numpy as np

In [25]:
liste2=np.array(liste)
liste2+=1
liste2

array([2, 3, 4])

In [26]:
liste2*5

array([10, 15, 20])

In [27]:
liste=[1,2,3,"4"]
type(liste)

list

In [29]:
dizi=np.array(liste)
dizi

array(['1', '2', '3', '4'], dtype='<U11')

In [30]:
type(dizi)

numpy.ndarray

In [31]:
dizi.shape

(4,)

In [32]:
dizi.ndim

1

In [33]:
liste2=([1,2])
liste2

[1, 2]

In [34]:
type(liste2)

list

In [35]:
liste2=([1,2],[3,4])
liste2  #bize verilen cevap () içinde ise tupledır

([1, 2], [3, 4])

In [36]:
type(liste2)

tuple

In [37]:
dizi2=np.array(liste2)
dizi2  #2*2 matris formatında cevap veriyor

array([[1, 2],
       [3, 4]])

In [38]:
dizi2.ndim  #2 boyutlu

2

In [39]:
dizi2.shape

(2, 2)

In [40]:
dizi2.fill(5)
dizi2  #tüm elemanları 5 ile doldurduk

array([[5, 5],
       [5, 5]])

In [41]:
#Matrisler

In [42]:
matris=np.array([[1,2,3],[4,5,6],[7,8,9]])
matris

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [44]:
matris.size  #9 elemanı var

9

In [45]:
matris.ndim

2

In [46]:
matris.shape

(3, 3)

In [47]:
matris[0,0]

1

In [48]:
matris[2,2]

9

In [51]:
matris[1,2]

6

In [52]:
matris[:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [53]:
matris[1:]

array([[4, 5, 6],
       [7, 8, 9]])

In [55]:
matris[:,1:]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [56]:
matris[:,1:2]

array([[2],
       [5],
       [8]])

In [58]:
matris[2,1]

8

In [59]:
matris[2,1]=35
matris[2,1]

35

In [60]:
#Copy , arange , random

In [61]:
matris=np.array([[1],[4],[7]])
matris

array([[1],
       [4],
       [7]])

In [62]:
matris.shape

(3, 1)

In [63]:
matris=np.array([[1,2,3],[4,5,6],[7,8,9]])
matris

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [64]:
matris.shape

(3, 3)

In [ ]:
#matris2 = matris dersek matristeki değişiklik matris2yi
#değiştirmiş olur değişiklik yansımasın istersek copy kullanırız

In [65]:
m1=np.array([[1,2,3],[4,5,6],[7,8,9]])
m1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [66]:
m2=m1.copy()

In [67]:
m1[1,1]=150
m1

array([[  1,   2,   3],
       [  4, 150,   6],
       [  7,   8,   9]])

In [68]:
m2  #değişiklik olmadı

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [69]:
m3=np.arange(0,10,2)
m3

array([0, 2, 4, 6, 8])

In [70]:
m4=np.arange(5,73,4)
m4

array([ 5,  9, 13, 17, 21, 25, 29, 33, 37, 41, 45, 49, 53, 57, 61, 65, 69])

In [71]:
m5=np.random.rand(1)  # 2 yazarsak 2 2,2 dersek 2*2 verir
m5

array([0.26208794])

In [72]:
dizi=np.array([[5,15,25],[35,45,55]])
dizi

array([[ 5, 15, 25],
       [35, 45, 55]])

In [73]:
np.sum(dizi)

180

In [74]:
np.prod(dizi)  #yanyana koyup çarptı

162421875

In [75]:
np.sum(dizi,axis=1) #satırlardaki kolon değerlerini topladı

array([ 45, 135])

In [76]:
np.prod(dizi,axis=1)

array([ 1875, 86625])

In [77]:
5*15*25

1875

In [78]:
35*45*55

86625

In [79]:
np.sum(dizi,axis=0)

array([40, 60, 80])

In [81]:
np.prod(dizi,axis=0)

array([ 175,  675, 1375])

In [82]:
dizi=np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
dizi

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [83]:
np.min(dizi)

1

In [86]:
dizi.min()

1

In [84]:
np.max(dizi)

9

In [87]:
dizi.max()

9

In [88]:
#bir fonksiyonun dizinin min noktası
dizi.argmin()

0

In [89]:
dizi.sum()

45

In [90]:
ortalama = 45/9
ortalama

5.0

In [91]:
dizi.mean()

5.0

In [92]:
dizi.mean(axis=0)  #her kolonun ortalamasını verir

array([4., 5., 6.])

In [93]:
dizi.mean(axis=1) #her satırın ortalaması

array([2., 5., 8.])

In [94]:
dizi

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [95]:
dizi.std()

2.581988897471611

In [96]:
dizi.std(axis=0)

array([2.44948974, 2.44948974, 2.44948974])

In [97]:
dizi.std(axis=1)

array([0.81649658, 0.81649658, 0.81649658])

In [98]:
dizi.var()

6.666666666666667

In [99]:
dizi.clip(2,5)  #2 değer arasında elemanlardan oluşsun
#diğerleri o değerlere dönüşür  1 2ye dönüştü
#6 5e dönüştü  7,8,9 5e dönüştü

array([[2, 2, 3],
       [4, 5, 5],
       [5, 5, 5]])

In [100]:
dizi2=np.random.rand(3,3)
dizi2

array([[0.28478178, 0.76141108, 0.97085588],
       [0.08308829, 0.57615646, 0.60086619],
       [0.22945375, 0.91659556, 0.39695504]])

In [101]:
dizi2=np.random.rand(3,3)*10
dizi2

array([[8.08911252, 4.71690481, 3.36029205],
       [5.38515916, 3.40678941, 3.01577737],
       [5.24190778, 9.83171454, 0.39867587]])

In [102]:
dizi2.round()  #yuvarladı

array([[ 8.,  5.,  3.],
       [ 5.,  3.,  3.],
       [ 5., 10.,  0.]])

In [103]:
dizi2

array([[8.08911252, 4.71690481, 3.36029205],
       [5.38515916, 3.40678941, 3.01577737],
       [5.24190778, 9.83171454, 0.39867587]])

In [104]:
dizi2=dizi2.round()
dizi2

array([[ 8.,  5.,  3.],
       [ 5.,  3.,  3.],
       [ 5., 10.,  0.]])

In [105]:
dizi3=np.random.rand(3,3)*10
dizi3

array([[0.84862547, 1.52791192, 8.2906809 ],
       [6.73541674, 5.17733676, 7.01272626],
       [8.51382472, 4.48380741, 9.96260457]])

In [106]:
#virgülden sonraki 2 basamağı gösterelim
dizi3.round(decimals=2)

array([[0.85, 1.53, 8.29],
       [6.74, 5.18, 7.01],
       [8.51, 4.48, 9.96]])

In [107]:
dizi=np.arange(5)
dizi

array([0, 1, 2, 3, 4])

In [109]:
dizi.shape

(5,)

In [115]:
dizi2=np.array([[0, 1, 2, 3, 4,5]])
dizi2

array([[0, 1, 2, 3, 4, 5]])

In [116]:
dizi2.shape

(1, 6)

In [118]:
dizi2.shape=3,2
dizi2

array([[0, 1],
       [2, 3],
       [4, 5]])

In [119]:
dizi2.reshape(1,6)

array([[0, 1, 2, 3, 4, 5]])

In [120]:
#transpoze
matris=np.array([[1,2,3],[4,5,6],[7,8,9]])
matris

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [121]:
matris.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [122]:
matris2=np.array([[10,20,30],[40,50,60],[70,80,90]])
matris2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [124]:
matris4=np.concatenate((matris,matris2))
matris4

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [125]:
matris4=np.concatenate((matris,matris2),axis=1)
matris4

array([[ 1,  2,  3, 10, 20, 30],
       [ 4,  5,  6, 40, 50, 60],
       [ 7,  8,  9, 70, 80, 90]])

In [126]:
np.vstack((matris,matris2))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [127]:
np.hstack((matris,matris2))

array([[ 1,  2,  3, 10, 20, 30],
       [ 4,  5,  6, 40, 50, 60],
       [ 7,  8,  9, 70, 80, 90]])

In [128]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [129]:
np.linspace(3,29,7)

array([ 3.        ,  7.33333333, 11.66666667, 16.        , 20.33333333,
       24.66666667, 29.        ])

In [130]:
#mantık işlemleri

In [134]:
dizi=np.array(["a","b"])
dizi2=np.array(["a","b"])
dizi3=np.array([1,2])
dizi4=np.array(["a",2])

In [135]:
dizi==dizi2

array([ True,  True])

In [136]:
dizi==dizi3

C:\Users\Bootcamp\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  """Entry point for launching an IPython kernel.


False

In [137]:
dizi==dizi4

array([ True, False])

In [138]:
dizi!=dizi4

array([False,  True])

In [139]:
d1=np.array([1,2])
d2=np.array([0,5])

In [140]:
d1<d2

array([False,  True])

In [142]:
#Problem1
#2*3 lük A ile 3*2lik B matrisini çarpın Cye eşitleyin

A= np.array(([1,2,3],[4,5,6]))
A

array([[1, 2, 3],
       [4, 5, 6]])

In [143]:
B= np.array(([10,20],[30,40],[50,60]))
B

array([[10, 20],
       [30, 40],
       [50, 60]])

In [144]:
C=np.dot(A,B)
C

array([[220, 280],
       [490, 640]])

In [ ]:
#Problem2
#iki basamaklı rastgele tamsayı 3*3 matris oluştur
#transpoze al

In [151]:
x=(np.random.rand(3,3)*100).round()
x

array([[72., 51.,  5.],
       [10., 13., 62.],
       [67., 72., 39.]])

In [152]:
x.T

array([[72., 10., 67.],
       [51., 13., 72.],
       [ 5., 62., 39.]])

In [153]:
#Problem3
#Ocak 2021 tüm günlerini yıl ay gün formatında array içine yazın

In [154]:
np.arange("2021-01","2021-02",dtype="datetime64[D]")
#D yazdık gün olarak görmek istediğimiz için

array(['2021-01-01', '2021-01-02', '2021-01-03', '2021-01-04',
       '2021-01-05', '2021-01-06', '2021-01-07', '2021-01-08',
       '2021-01-09', '2021-01-10', '2021-01-11', '2021-01-12',
       '2021-01-13', '2021-01-14', '2021-01-15', '2021-01-16',
       '2021-01-17', '2021-01-18', '2021-01-19', '2021-01-20',
       '2021-01-21', '2021-01-22', '2021-01-23', '2021-01-24',
       '2021-01-25', '2021-01-26', '2021-01-27', '2021-01-28',
       '2021-01-29', '2021-01-30', '2021-01-31'], dtype='datetime64[D]')

In [155]:
np.arange("2021-01","2022-02",dtype="datetime64[M]")
#M yazdık ay olarak görmek istediğimiz için

array(['2021-01', '2021-02', '2021-03', '2021-04', '2021-05', '2021-06',
       '2021-07', '2021-08', '2021-09', '2021-10', '2021-11', '2021-12',
       '2022-01'], dtype='datetime64[M]')

In [156]:
import calendar
print(calendar.month(2021,1))

    January 2021
Mo Tu We Th Fr Sa Su
             1  2  3
 4  5  6  7  8  9 10
11 12 13 14 15 16 17
18 19 20 21 22 23 24
25 26 27 28 29 30 31



In [ ]:
#Internet Hız ölçümü  
#indirme ve yükleme  hızımızı ölçelim


In [157]:
!pip install speedtest-cli

In [158]:
import speedtest

In [162]:
test=speedtest.Speedtest()
indirme=test.download()
gonderme=test.upload()
indirme=indirme/1000000
gonderme=gonderme/1000000
print("İndirme Hızı: %d" %((indirme)))
print("Gönderme Hızı: %d" %((gonderme)))

ConfigRetrievalError: HTTP Error 403: Forbidden