In [1]:
#https://www.udemy.com/course/draft/1949346/learn/lecture/12033600?start=0#overview
#6,5 saat

In [3]:
#math, datetime, statistics, numpy,scipy,pandas,matplotlib
#Exception handling, Threading, sql, sqlite, tkinter

In [4]:
#PYcharm indirildi

In [5]:
lst=[8,5,6,2,5,4,1]
lst.append(4)
lst.append([4,5,6,4,5])
lst.extend([1,2,3])
lst

[8, 5, 6, 2, 5, 4, 1, 4, [4, 5, 6, 4, 5], 1, 2, 3]

In [6]:
lst.insert(2,15)  #ikinci indexi 15 yap dedik
lst

[8, 5, 15, 6, 2, 5, 4, 1, 4, [4, 5, 6, 4, 5], 1, 2, 3]

In [7]:
lst.pop()

3

In [8]:
lst

[8, 5, 15, 6, 2, 5, 4, 1, 4, [4, 5, 6, 4, 5], 1, 2]

In [9]:
lst.pop(-3)  #dersek [4,5,6,4,5] silinecek
lst

[8, 5, 15, 6, 2, 5, 4, 1, 4, 1, 2]

In [10]:
sum(lst)

53

In [11]:
lst.sort()

In [12]:
lst

[1, 1, 2, 2, 4, 4, 5, 5, 6, 8, 15]

In [13]:
lst.reverse()

In [14]:
lst

[15, 8, 6, 5, 5, 4, 4, 2, 2, 1, 1]

In [15]:
sqlist=[e**2 for e in lst]
sqlist

[225, 64, 36, 25, 25, 16, 16, 4, 4, 1, 1]

In [16]:
temp=[20,22,23,24,25,25.6,26.7,25,24]
F=[e*9/5+32 for e in temp]
F

[68.0, 71.6, 73.4, 75.2, 77.0, 78.08, 80.06, 77.0, 75.2]

In [17]:
t=[5,1,2,4,5,2,1]
t.index(4)

3

In [18]:
t[0]

5

In [19]:
#set objeleri index ile data almamızı desteklemez

In [20]:
class IotDevices:
    def __init__(self):
        print("An object of class IotDevices has been created")
        
Raspi=IotDevices()    

An object of class IotDevices has been created


In [21]:
Raspi=IotDevices("Raspi","Controller",3500)   

TypeError: __init__() takes 1 positional argument but 4 were given

In [23]:
class IotDevices:
    def __init__(self,name,type,cost):
        print("An object of class IotDevices has been created")
        self.name=name
        self.type=type
        self.cost=cost
Raspi=IotDevices("Raspi","Controller",3500)   

An object of class IotDevices has been created


In [24]:
print("The device name is ",Raspi.name)
print("Type is ",Raspi.type)
print("Cost",Raspi.cost)

The device name is  Raspi
Type is  Controller
Cost 3500


In [25]:
device1=IotDevices("Raspi","Controller",3500) 
print("The device name is ",device1.name)
print("Type is ",device1.type)
print("Cost",device1.cost)

An object of class IotDevices has been created
The device name is  Raspi
Type is  Controller
Cost 3500


In [26]:
device2=IotDevices("DMM","Equipment",500) 
print(device2.name,device2.cost)

An object of class IotDevices has been created
DMM 500


In [30]:
class IotDevices:
    def __init__(self,name,type,cost):
        print("An object of class IotDevices has been created")
        self.name=name
        self.type=type
        self.cost=cost

    def printDetails(self):
        print("The name of the device is ",self.name)
        print("It is of type",self.type)
        print("Cost",self.cost)

In [32]:
device1=IotDevices("Raspi","Controller",3500) 
device2=IotDevices("DMM","Equipment",500) 

An object of class IotDevices has been created
An object of class IotDevices has been created


In [33]:
device1.printDetails()
device2.printDetails()

The name of the device is  Raspi
It is of type Controller
Cost 3500
The name of the device is  DMM
It is of type Equipment
Cost 500


In [38]:
class IotDevices:
    __count=0
    def __init__(self,name,type,cost):
        print("An object of class IotDevices has been created")
        self.name=name
        self.type=type
        self.cost=cost
        IotDevices.__count+=1

    def printDetails(self):
        print("The name of the device is ",self.name)
        print("It is of type",self.type)
        print("Cost",self.cost)
        
    #staticmethod
    def get_count():
        return IotDevices.__count

In [40]:
device1=IotDevices("Raspi","Controller",3500) 
print("Count= ",IotDevices.get_count())
device2=IotDevices("DMM","Equipment",500)
print("Count= ",device2.get_count())
device1.printDetails()
device2.printDetails()

An object of class IotDevices has been created
Count=  3
An object of class IotDevices has been created


TypeError: get_count() takes 0 positional arguments but 1 was given

In [1]:
#Programming Aspect of Networking

In [ ]:
#2 adet dosya oluşturduk
#client.py ve server.py 

In [ ]:
#client.py
#create a socket ip ve port numarası barındırsın
#connect to socket to server socket
#communicate
#close the socket

In [2]:
#server.py
#create a socket
#bind socket to particular port number
#listen for clients
#accept the client connection
#communicate
#close active connection
#close ther server socket

In [3]:
#Write client and server code

In [4]:
#client.py
#import the socket module
import socket
client_socket=socket.socket()
client_socket.connect(("localhost",2000))
#localhostta çalışacağı için localhost dedik 2000 de porttur
client_socket.sendall("Hi server. I am a client.".encode())
data=client_socket.recv(1000)
print(data.decode())
client_socket.close()

In [8]:
#server.py
#import socket module
import socket
server_socket=socket.socket()
port_number=2000
server_socket.bind(("",port_number))
print("Server is bound to port number ",port_number)
server_socket.listen()
print("Server is listening for client")
#1234 de porttur
conn,addr=server_socket.accept()
print("Hey got a client from address",addr)
data=conn.recv(1000)  #byte
print(data.decode())
conn.sendall("Hey from server".encode())
conn.close()
server_socket.close()

In [9]:
#Şimdi bu haliyle çoklu işlemlere izin vermez şimdi de onu yapalım

In [10]:
#Multithreading

In [11]:
#from threading module , we need to import Thread class
#for creating multithreading objects
from threading import Thread  
import time

def f1(arg):
    print("Hi from f1 with argument"+str(arg))
    time.sleep(5)
    print("Hi, f1 woke up with argument"+str(arg))

"""t1=Thread(target=f1)
t1.start()
print("Hi from main")
time.sleep(5)
print("Hi main got up")
t1.join()
"""
for i in range(10):
    t=Thread(target=f1,args=(i,))
    t.start()

Hi from f1 with argument0
Hi from f1 with argument1
Hi from f1 with argument2
Hi from f1 with argument3
Hi from f1 with argument4
Hi from f1 with argument5
Hi from f1 with argument6
Hi from f1 with argument7
Hi from f1 with argument8
Hi from f1 with argument9
Hi, f1 woke up with argument2
Hi, f1 woke up with argument1
Hi, f1 woke up with argument0
Hi, f1 woke up with argument6Hi, f1 woke up with argument5Hi, f1 woke up with argument3
Hi, f1 woke up with argument4


Hi, f1 woke up with argument8Hi, f1 woke up with argument7
Hi, f1 woke up with argument9



In [12]:
#Working with ChatBot
#client ve server dosyalarımız var yine

In [14]:
#client.py
import socket
from threading import Thread

client_socket=socket.socket()
client_socket.connect(("localhost",2000))
print("Connected to server")

def receive_data():
    while True:
        data=client_socket.recv(1000)
        print("Server:",data.decode())
             
def sending_data():
    while True:
        user_input=input()
        client_socket.sendall(user_input.decode())
    
t=Thread(target=receive_data)
t.start()
sending_data()

ConnectionRefusedError: [WinError 10061] Hedef makine etkin olarak reddettiğinden bağlantı kurulamadı

In [ ]:
#server.py
import socket
from threading import Thread

server_socket=socket.socket()
port_number=2000
server_socket.bind(("",port_number))
print("Server is bound to port number ",port_number)
server_socket.listen()
print("Server is listening to clients")
conn,addr=server_socket.accept()
print("Got a client from address",addr)

def receive_data():
    while True:
        data=conn.recv(1000)
        print("Client",data.decode())
        
def send_data():
    while True:
        user_input=input()
        conn.sendall(user_input.encode())

t=Thread(target=receive_data)
t.start()
send_data()

Server is bound to port number  2000
Server is listening to clients


In [13]:
#ChatApp 
#Creating and Importing Client Socket

In [1]:
#client.py ve server.py yine var

In [ ]:
#client.py
import socket
from threading import Thread

cs=socket.socket()
cs.connect(("localhost",2000))
name=input("Enter your name: ")
cs.sendall(name.encode())

def receive_data():
    while True:
        data=cs.recv(1000)
        print(data.decode())
             
def send_data():
    while True:
        user_input=input()
        cs.sendall(user_input.decode())
    
t=Thread(target=receive_data)
t.start()
send_data()

In [ ]:
#server.py
import socket
from threading import Thread

ss=socket.socket()
port_number=2000
ss.bind(("",port_number))
#print("Server is bound to port number ",port_number)
ss.listen()
#print("Server is listening to clients")
clients={}


def client_task(client_name,client_conn,client_addr):
    while True:
        data=client_conn.recv(1000)
        message=client_name+": "+data.decode()
        for client in clients:
            if client!=client_name:
                clients[client].sendall(message.encode())

while True:
    conn,addr=ss.accept()
    print("Got a connection from client at address",addr)
    name=conn.recv(1000)
    clients[name.decode()]=conn
    t=Thread(target=client_task,args=(name.decode(),conn,addr))
    t.start()

"""
def receive_data():
    while True:
        data=conn.recv(1000)
        print("Client",data.decode())
        
def send_data():
    while True:
        user_input=input()
        conn.sendall(user_input.encode())

t=Thread(target=receive_data)
t.start()
send_data()
"""

In [1]:
#Pycharm and DB

In [ ]:
sqlite3 company.db #oluştururuz

In [ ]:
create table employee (id,fname,lname,salary,email,dob);

In [ ]:
.tables  #deyince tabloları verir

In [ ]:
.header on

In [ ]:
select * from employee;

In [ ]:
drop table employee;

In [ ]:
.tables #deyince gelmiyor tablo

In [ ]:
create table employee (id INTEGER PRIMARY_KEY AUTO_INCREMENT,fname VARCHAR(20) NOT NULL,lname VARCHAR(20),salary INT,email VARCHAR(20),dob DATE);

In [ ]:
.tables

In [ ]:
.schema

In [ ]:
#Insert Values

In [ ]:
insert into employee (fname,email,dob) values("xyz","xyz@company.com","1984-05-18")

In [ ]:
insert into employee (fname,lname,email,dob) values("pqr","st","pqr@company.com","1994-06-18")

In [ ]:
insert into employee (fname,lname,email,dob) values("xyz","st","xyz@company.com","1974-08-15")

In [ ]:
.tables

In [ ]:
select * from employee;

In [ ]:
.exit #ile çıkış yaptık

In [ ]:
#connecting db and python code

In [ ]:
#connecto sqlite.py
import sqlite3

connection=sqlite3.connect("school.db")

cursor=connection.cursor()

query=''' create table students (rn INTEGER,name VARCHAR(20),gender VARCHAR(1),dob DATE);'''
cursor.execute(query)

query=''' create table teachers (id INTEGER,name VARCHAR(20),gender VARCHAR(1),dob DATE);'''
cursor.execute(query)

query=''' insert into students (rn ,name,gender) values(12,"xyz","M");'''
cursor.execute(query)

query=''' insert into students (rn ,name,gender) values(45,"pqr","F");'''
cursor.execute(query)

query=''' insert into students (rn ,name,gender) values(54,"abc","F");'''
cursor.execute(query)

query=''' insert into teachers (id ,name,gender) values(12,"rst","M");'''
cursor.execute(query)

query=''' insert into teachers (id ,name,gender) values(13,"wxy","F");'''
cursor.execute(query)

query=''' insert into teachers (id ,name,gender) values(14,"def","M");'''
cursor.execute(query)

connection.commit()
connection.close()

In [ ]:
#reading from db.py

import sqlite3

connection=sqlite3.connect("school.db")

cursor=connection.cursor()
print("Student details")
query='select * from students where gender="M";'
cursor.execute(query)
result=cursor.fetchall()
#print(result)
for student in result:
    print(student)
print("Teacher details")
query='select * from teachers where gender="F";'
cursor.execute(query)
result=cursor.fetchall()
#print(result)
for teacher in result:
    print(teacher)
connection.close()

In [2]:
#ChatApp değişiklik yapalım

In [ ]:
#client.py
import socket
from threading import Thread

cs=socket.socket()
cs.connect(("localhost",2000))
"""client_info={}
client_info["name"] =input("Enter your name: ")
client_info["email"]=input("Enter your email: ")
client_str=client_
"""  #buradan vazgeçtik
name =input("Enter your name: ")
email=input("Enter your email: ")
#client_info="name:"+name+","+"email"+email  kapattık sonradan
client_info=name+","+email
cs.sendall(client_info.encode())

def receive_data():
    while True:
        data=cs.recv(1000)
        print(data.decode())
             
def send_data():
    while True:
        user_input=input()
        cs.sendall(user_input.decode())
    
t=Thread(target=receive_data)
t.start()
send_data()

In [ ]:
#server.py
import sqlite3
import socket
from threading import Thread

connection=sqlite3.connection("chat.db")
cursor=connection.cursor()

#cursor.execute("create table clients (name VARCHAR(20),email VARCHAR(20),addr VARCHAR(20));")
cursor.execute('select * from clients;')
result=cursor.fetchall()
print(result)

ss=socket.socket()
port_number=2000
ss.bind(("",port_number))
#print("Server is bound to port number ",port_number)
ss.listen()
#print("Server is listening to clients")
clients={}


def client_task(client_name,client_conn,client_addr):
    while True:
        data=client_conn.recv(1000)
        message=client_name+": "+data.decode()
        for client in clients:
            if client!=client_name:
                clients[client].sendall(message.encode())

while True:
    conn,addr=ss.accept()
    #patlayınca print(addr) ve print(type(addr)) ekleyip baktık tuple verdi
    client_info=conn.recv(1000)
    client_info=client_info.decode()
    client_info_lst=client_info.split(",")
   # name=client_info_lst[0].split(":") kapattık
    name=client_info_lst[0]
    email=client_info_lst[1]
    query='''INSERT INTO clients (name,email,addr) values("{0}","{1}","{2}");'''.format(name,email,addr[0])
    cursor.execute(query)
    connection.commit()
    print("Got a connection from client at address",addr,"and name",name)
    print("Clients registered as of date now")
    result=cursor.fetchall()
    print(result)
    clients[name]=conn
    t=Thread(target=client_task,args=(name,conn,addr))
    t.start()

"""
def receive_data():
    while True:
        data=conn.recv(1000)
        print("Client",data.decode())
        
def send_data():
    while True:
        user_input=input()
        conn.sendall(user_input.encode())

t=Thread(target=receive_data)
t.start()
send_data()
"""

In [3]:
client_info = "name:xyz,email:xyz@company.com"

In [4]:
client_info.split(",")

['name:xyz', 'email:xyz@company.com']

In [5]:
client_info_lst=client_info.split(",")

In [6]:
client_info_lst[0].split(":")

['name', 'xyz']

In [8]:
name=client_info_lst[0]
name

'name:xyz'

In [ ]:
#üstteki client server için okuma yapalım

#reading from db.py

import sqlite3

connection=sqlite3.connect("chat.db")

cursor=connection.cursor()
print("Clients details")
query='select * from clients;'
cursor.execute(query)
result=cursor.fetchall()
print(result)

"""for student in result:
    print(student)
print("Teacher details")
query='select * from teachers where gender="F";'
cursor.execute(query)
result=cursor.fetchall()
#print(result)
for teacher in result:
    print(teacher)
"""
connection.close()

In [ ]:
#Add email and client name

In [ ]:
#server.py
import sqlite3
import socket
from threading import Thread

connection=sqlite3.connection("chat.db")
cursor=connection.cursor()

cursor.execute("drop table clients")
cursor.execute("create table clients (name VARCHAR(20),email VARCHAR(20),addr VARCHAR(20));")
#cursor.execute('select * from clients;')
#result=cursor.fetchall()
#print(result)

ss=socket.socket()
port_number=2000
ss.bind(("",port_number))
#print("Server is bound to port number ",port_number)
ss.listen()
#print("Server is listening to clients")
clients={}


def client_task(client_name,client_conn,client_addr):
    while True:
        data=client_conn.recv(1000)
        connection=sqlite3.connect("chat.db")
        cursor=connection.cursor()
        cursor.execute('select * from clients where name="{}";'.format(client_name))
        result=cursor.fetchall()
        print(result[0][0],"sent a message")
        message=client_name+" {()}".format(result[0][1])+": "+data.decode()
        for client in clients:
            if client!=client_name:
                clients[client].sendall(message.encode())

while True:
    conn,addr=ss.accept()
    #patlayınca print(addr) ve print(type(addr)) ekleyip baktık tuple verdi
    client_info=conn.recv(1000)
    client_info=client_info.decode()
    client_info_lst=client_info.split(",")
   # name=client_info_lst[0].split(":") kapattık
    name=client_info_lst[0]
    email=client_info_lst[1]
    query='''INSERT INTO clients (name,email,addr) values("{0}","{1}","{2}");'''.format(name,email,addr[0])
    cursor.execute(query)
    connection.commit()
    print("Got a connection from client at address",addr,"and name",name)
    print("Clients registered as of date now")
    result=cursor.fetchall()
    print(result)
    clients[name]=conn
    t=Thread(target=client_task,args=(name,conn,addr))
    t.start()

"""
def receive_data():
    while True:
        data=conn.recv(1000)
        print("Client",data.decode())
        
def send_data():
    while True:
        user_input=input()
        conn.sendall(user_input.encode())

t=Thread(target=receive_data)
t.start()
send_data()
"""

In [9]:
#Data Analysis

In [10]:
import numpy as np

In [13]:
temp=[20.1,20,8,21.9,22.5,22.7,22.3,21.2,20.9,20.1]
temp_far=[np.round(i*1.8) for i in temp ]
temp_far

[36.0, 36.0, 14.0, 39.0, 40.0, 41.0, 40.0, 38.0, 38.0, 36.0]

In [16]:
lst=[24,12,57]
nplst=np.array(lst)
print(nplst)
print(type(nplst))

[24 12 57]
<class 'numpy.ndarray'>


In [17]:
lst1=[e**2 for e in lst]
print(lst1)

[576, 144, 3249]


In [18]:
from sys import getsizeof as size

In [19]:
print(lst)

[24, 12, 57]


In [23]:
size_of_list=size(lst)
size_of_list

88

In [21]:
empty_lst=[]
size(empty_lst)

64

In [24]:
size(lst[0])

28

In [25]:
total_size=size_of_list+len(lst)*size(lst[0])
total_size

172

In [ ]:
#memory consumed by ndarray

In [26]:
print(nplst)

[24 12 57]


In [27]:
size(nplst)

116

In [28]:
lst=[24,12,57,84,45,45,12,12,14,15,13]
nplst=np.array(lst)
size(nplst)

148

In [29]:
total_size=size_of_list+len(lst)*size(lst[0])
total_size

396

In [ ]:
#396 ile 148 arasında fark var küçülme oldu

In [30]:
#time comparison list and numpy array

In [31]:
import time

In [32]:
def cal_time_python_version():
    t1=time.time()
    X=range(1000)
    Y=range(1000)
    Z=[X[i]+Y[i] for i in range(len(X))]
    t2=time.time()
    return t2-t1

In [33]:
def cal_time_numpy_version():
    t1=time.time()
    X=np.arange(1000)
    Y=np.arange(1000)
    Z=X+Y
    t2=time.time()
    return t2-t1

In [35]:
print(cal_time_numpy_version(),cal_time_python_version())

0.0010001659393310547 0.0


In [36]:
for i in range(10):
    print(cal_time_numpy_version(),cal_time_python_version())

0.0 0.0
0.0 0.0009999275207519531
0.0 0.0
0.0 0.0
0.0010035037994384766 0.0
0.0 0.0009968280792236328
0.0 0.0
0.0 0.0
0.0 0.0010008811950683594
0.0009992122650146484 0.0010023117065429688


In [37]:
#Create numpy arrays

In [38]:
a=np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
type(a)

numpy.ndarray

In [41]:
a=np.arange(10.4)
a

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [42]:
a=np.arange(0.3,10.5)
a

array([ 0.3,  1.3,  2.3,  3.3,  4.3,  5.3,  6.3,  7.3,  8.3,  9.3, 10.3])

In [43]:
a=np.arange(0.3,10.5,2)
a

array([ 0.3,  2.3,  4.3,  6.3,  8.3, 10.3])

In [45]:
a=np.arange(10.5,0.3,-2)
a

array([10.5,  8.5,  6.5,  4.5,  2.5,  0.5])

In [46]:
a=np.arange(0.3,10.5,0.7)
a

array([ 0.3,  1. ,  1.7,  2.4,  3.1,  3.8,  4.5,  5.2,  5.9,  6.6,  7.3,
        8. ,  8.7,  9.4, 10.1])

In [48]:
a=np.linspace(1,10)
a


array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [49]:
type(a)

numpy.ndarray

In [50]:
a=np.linspace(1,10,7)
print(a)
print(type(a))

[ 1.   2.5  4.   5.5  7.   8.5 10. ]
<class 'numpy.ndarray'>


In [52]:
#Zero Dim
x=np.array(42)
print(x)
print(type(x))
print(np.ndim(x))

42
<class 'numpy.ndarray'>
0


In [55]:
#1 dim
A=np.array([1,2,3,2,1,4,5,2,1,2,3])
B=np.array([1.1,2.5,6.2,1.2,1.5,8.5])
print(A)
print(B)
print(A.dtype)
print(B.dtype)
print(A.ndim)
print(B.ndim)
print(np.ndim(A),np.ndim(B))

[1 2 3 2 1 4 5 2 1 2 3]
[1.1 2.5 6.2 1.2 1.5 8.5]
int32
float64
1
1
1 1


In [56]:
#Two and multidimensional array

In [57]:
A=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(A)
print(A.ndim)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2


In [58]:
A=np.array([[[1,2],[3,4]],
            [[4,5],[6,7]],
            [[7,8],[9,10]]])
print(A)
print(A.ndim)

[[[ 1  2]
  [ 3  4]]

 [[ 4  5]
  [ 6  7]]

 [[ 7  8]
  [ 9 10]]]
3


In [60]:
#shape of array
x=np.array([[67,12,15],
           [77,56,45],
           [45,78,45],
           [45,12,15],
           [78,98,45],
           [45,58,59]]
)
print(np.shape(x))
print(x.shape)

(6, 3)
(6, 3)


In [62]:
x.shape=(3,6)
print(x)

[[67 12 15 77 56 45]
 [45 78 45 45 12 15]
 [78 98 45 45 58 59]]


In [63]:
x.shape=(6,3)
print(x)

[[67 12 15]
 [77 56 45]
 [45 78 45]
 [45 12 15]
 [78 98 45]
 [45 58 59]]


In [64]:
x=np.array([[67,12,15,12],
           [77,56,45,18],
           [45,78,45,19],
           [45,12,15,18],
           [78,98,45,54],
           [45,58,59,14]]
)
print(np.shape(x))
print(x.shape)

(6, 4)
(6, 4)


In [65]:
x.shape=(6,4)
print(x)

[[67 12 15 12]
 [77 56 45 18]
 [45 78 45 19]
 [45 12 15 18]
 [78 98 45 54]
 [45 58 59 14]]


In [66]:
x[2]

array([45, 78, 45, 19])

In [67]:
x[2][2]

45

In [69]:
temp=x[2]
temp

array([45, 78, 45, 19])

In [70]:
temp[2]

45

In [71]:
x[2,2]

45

In [72]:
x[-1]

array([45, 58, 59, 14])

In [73]:
x[-1,-2]

59

In [74]:
y=np.array([8,9,5,4,5,2,1,2,0,2,4,7])
y[3:5]

array([4, 5])

In [75]:
y[:6]

array([8, 9, 5, 4, 5, 2])

In [76]:
y[3:]

array([4, 5, 2, 1, 2, 0, 2, 4, 7])

In [77]:
x[1:3,2:4]

array([[45, 18],
       [45, 19]])

In [78]:
x[1:,2:4]

array([[45, 18],
       [45, 19],
       [15, 18],
       [45, 54],
       [59, 14]])

In [79]:
x[:,:4]

array([[67, 12, 15, 12],
       [77, 56, 45, 18],
       [45, 78, 45, 19],
       [45, 12, 15, 18],
       [78, 98, 45, 54],
       [45, 58, 59, 14]])

In [80]:
x[:,2:]

array([[15, 12],
       [45, 18],
       [45, 19],
       [15, 18],
       [45, 54],
       [59, 14]])

In [81]:
x[:,:]

array([[67, 12, 15, 12],
       [77, 56, 45, 18],
       [45, 78, 45, 19],
       [45, 12, 15, 18],
       [78, 98, 45, 54],
       [45, 58, 59, 14]])

In [83]:
y[3::2]

array([4, 2, 2, 2, 7])

In [86]:
x[::2,:]

array([[67, 12, 15, 12],
       [45, 78, 45, 19],
       [78, 98, 45, 54]])

In [87]:
x[::2,::2]  #2 satır atla 2 sütun atla göster

array([[67, 15],
       [45, 45],
       [78, 45]])

In [88]:
x[::2,::3] 

array([[67, 12],
       [45, 19],
       [78, 54]])

In [89]:
#array of ones and zeros

In [92]:
O=np.ones((8,10),dtype=int)
print(O)

[[1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]]


In [91]:
Z=np.zeros((10,15))
Z

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [97]:
row,col=[int(e) for e in input("Enter the shape of the array").split(",")]
A=np.ones((row,col),dtype=int)

for i in range(row):
    for j in range(col):
        A[i,j]=i*j
print(A)

Enter the shape of the array3,4
[[0 0 0 0]
 [0 1 2 3]
 [0 2 4 6]]


In [98]:
row,col=[int(e) for e in input("Enter the shape of the array").split(",")]
A=np.ones((row,col),dtype=int)

for i in range(row):
    for j in range(col):
        A[i,j]=i*j
print(A)

Enter the shape of the array5,9
[[ 0  0  0  0  0  0  0  0  0]
 [ 0  1  2  3  4  5  6  7  8]
 [ 0  2  4  6  8 10 12 14 16]
 [ 0  3  6  9 12 15 18 21 24]
 [ 0  4  8 12 16 20 24 28 32]]


In [99]:
x=np.array([2,5,18,12,14,1,15])
X=np.ones_like(x)
print(X)
Y=np.zeros_like(x)
print(Y)

[1 1 1 1 1 1 1]
[0 0 0 0 0 0 0]


In [100]:
y=x.copy()
y

array([ 2,  5, 18, 12, 14,  1, 15])

In [103]:
np.identity(5,dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [104]:
np.eye(5,9)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.]])

In [105]:
np.eye(5,9,dtype=int)

array([[1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0]])

In [106]:
np.eye(5,9,k=1,dtype=int)  #1 kolon sağdan başladı

array([[0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0]])

In [107]:
np.eye(5,9,k=-1,dtype=int)  #1 satır alttan başladı

array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0]])

In [110]:
x

array([ 2,  5, 18, 12, 14,  1, 15])

In [108]:
x+3

array([ 5,  8, 21, 15, 17,  4, 18])

In [109]:
x//2

array([1, 2, 9, 6, 7, 0, 7], dtype=int32)

In [111]:
x**2

array([  4,  25, 324, 144, 196,   1, 225], dtype=int32)

In [113]:
A=np.array([[11,12,13],[21,22,23],[31,32,33]])
B=np.ones((3,3),dtype=int)
print(A)
print(B)

[[11 12 13]
 [21 22 23]
 [31 32 33]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [114]:
A+B

array([[12, 13, 14],
       [22, 23, 24],
       [32, 33, 34]])

In [115]:
A-B

array([[10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [116]:
A*B

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [117]:
#Matrix multiplication

In [118]:
A//B

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]], dtype=int32)

In [119]:
A**B

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]], dtype=int32)

In [120]:
np.dot(A,B)

array([[36, 36, 36],
       [66, 66, 66],
       [96, 96, 96]])

In [121]:
X=np.array([[[3,1,2],
           [5,2,1],
           [4,1,1]],
            [[3,2,4],
            [2,1,5],
            [3,5,4]],
            [[2,1,4],
            [5,4,1],
            [6,5,1]]])
Y=np.ones_like(X)
print(X)
print(Y)

[[[3 1 2]
  [5 2 1]
  [4 1 1]]

 [[3 2 4]
  [2 1 5]
  [3 5 4]]

 [[2 1 4]
  [5 4 1]
  [6 5 1]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


In [122]:
np.dot(X,Y)

array([[[[ 6,  6,  6],
         [ 6,  6,  6],
         [ 6,  6,  6]],

        [[ 8,  8,  8],
         [ 8,  8,  8],
         [ 8,  8,  8]],

        [[ 6,  6,  6],
         [ 6,  6,  6],
         [ 6,  6,  6]]],


       [[[ 9,  9,  9],
         [ 9,  9,  9],
         [ 9,  9,  9]],

        [[ 8,  8,  8],
         [ 8,  8,  8],
         [ 8,  8,  8]],

        [[12, 12, 12],
         [12, 12, 12],
         [12, 12, 12]]],


       [[[ 7,  7,  7],
         [ 7,  7,  7],
         [ 7,  7,  7]],

        [[10, 10, 10],
         [10, 10, 10],
         [10, 10, 10]],

        [[12, 12, 12],
         [12, 12, 12],
         [12, 12, 12]]]])

In [123]:
MA=np.mat(A)
MB=np.mat(B)
print(MA*MB)

[[36 36 36]
 [66 66 66]
 [96 96 96]]


In [124]:
#Comparison operations

In [125]:
A=np.array([[1,2,3],
           [4,5,6],
           [7,8,9]])
B=np.array([[1,5,3],
            [3,5,2],
            [4,9,9]])
print(A==B)

[[ True False  True]
 [False  True False]
 [False False  True]]


In [126]:
np.array_equal(A,B)

False

In [127]:
np.array_equal(A,A)

True

In [132]:
a=np.array([[True,True],
           [False,False]])
b=np.array([[True,False],
           [True,False]])
print(np.logical_and(a,b))

[[ True False]
 [False False]]


In [135]:
print(np.logical_not(a))

[[False False]
 [ True  True]]


In [137]:
print(np.logical_or(a,b))

[[ True  True]
 [ True  True]]


In [131]:
print(np.logical_xor(a,b))

[[ True  True]
 [ True  True]]
