# Pseudorandom Number Generation

In [1]:
import numpy as np

In [2]:
samples1 = np.random.randn(5)
samples1

array([ 0.16384708, -1.22126576, -0.4965789 ,  0.61651003,  0.88132688])

In [3]:
np.random.randn()

-0.15285942505519598

In [4]:
samples2 = np.random.randn(2, 3)
samples2

array([[-0.13658023,  1.07912797, -0.54776311],
       [-1.67413444, -0.55746977, -0.26385356]])

In [5]:
np.random.randn(2, 3, 2)

array([[[-1.40865516, -0.49004049],
        [ 0.90549767, -0.72786223],
        [-1.6157862 ,  1.00580351]],

       [[-1.89237188, -1.93228305],
        [ 0.52600826, -0.79369392],
        [-1.67258427, -0.13308885]]])

In [6]:
samples3 = np.random.normal(size=(4, 4))
samples3

array([[-0.90961652, -1.57413552, -0.06455246,  0.39776886],
       [-0.19504926,  2.11074017,  0.52867939, -1.3182997 ],
       [ 1.03578386, -0.68057955, -0.41629194,  0.63967149],
       [ 0.77172093, -0.30247931, -0.52927727, -1.03469422]])

In [7]:
from numpy.random import *

In [8]:
seed(1234)

In [9]:
seed(1234)
x = randn(10)
x

array([ 0.47143516, -1.19097569,  1.43270697, -0.3126519 , -0.72058873,
        0.88716294,  0.85958841, -0.6365235 ,  0.01569637, -2.24268495])

In [10]:
y =rand(10)
y

array([0.68346294, 0.71270203, 0.37025075, 0.56119619, 0.50308317,
       0.01376845, 0.77282662, 0.88264119, 0.36488598, 0.61539618])

In [19]:
z = randint(10, 20)
z

12

In [16]:
zs = randint(10, 30, size=(2, 5), dtype='int64' ) # use float to convert integers in to float values
zs

array([[23, 26, 19, 18, 22],
       [16, 22, 29, 25, 27]], dtype=int64)

In [18]:
randint(10, 30).reshape(2, 10)

AttributeError: 'int' object has no attribute 'reshape'

In [20]:
randn(10).reshape(2, 5)

array([[-1.00655134,  0.00769448,  1.23084078,  2.00074455, -0.6721939 ],
       [ 0.91388772, -0.40461981,  2.30728121, -0.47127242, -1.21870147]])

In [16]:
rand = RandomState(1234)

In [17]:
rand.rand(10)

array([0.19151945, 0.62210877, 0.43772774, 0.78535858, 0.77997581,
       0.27259261, 0.27646426, 0.80187218, 0.95813935, 0.87593263])

In [18]:
rand.randint(10)

8

In [19]:
rand.randn(10)

array([ 2.00254961,  0.01086208, -0.86924706,  1.4249841 ,  0.1458091 ,
        2.89409095, -0.30426018,  0.861661  , -0.68992667,  0.18749737])

In [20]:
rand.normal(10)

10.604308742162978

In [21]:
rand.uniform(10)

4.137596710960803