In [1]:
#https://www.udemy.com/course/learn-core-python-numpy-and-pandas/learn/lecture/14484446?start=15#overview
#3 saat

#colab dokümanları indirilemedi

In [1]:
import numpy as np

In [4]:
i=0
while i<20:
    if(i%2==0):
        i=i+1
        continue
    print(i)
    i=i+1

#1 3 5 7 9 11 13 15 17 19 verir

1
3
5
7
9
11
13
15
17
19


In [5]:
words = ["The","age","of","reason"]
x="The" in words
print(x) # True döner



True


In [6]:
nums = [3,4,8]
x= 10 not in nums
print(x) # True döner



True


In [ ]:
nums.append(14)
len(nums)
nums.insert(2,100) #2.index 100 ekler
nums.index(10) #ilk olarak kaçıncı indexte yer aldığını verir
max(nums)
min(nums)
nums.reverse() #matrisin tersini gösterir
nums.remove() #sondan siler



In [ ]:
num=[5,8,10,12,10]
while 10 in nums:
    nums.remove(10)
#tüm 10ları sil dedik



In [8]:
#Functions:
def name_of_philospher(name,country):
    print(name,country)

name_of_philospher("Russell","UK")

Russell UK


In [9]:
def name_of_philospher(name,country):
    str = "The philo {} lived in country {}".format(name,country)
    return str

str = name_of_philospher("Russell","UK")
print(str)




The philo Russell lived in country UK


In [10]:
def add_and_subtract(num1,num2):
    add=num1+num2
    diff=num1-num2
    return add,diff

add,diff = add_and_subtract(10,2)
print("The sum is =", add)
print("The difference is =",diff)

The sum is = 12
The difference is = 8


In [12]:
add,diff = add_and_subtract(num1=10,num2=2)
print("The sum is =", add)
print("The difference is =",diff)

The sum is = 12
The difference is = 8


In [14]:
add,diff = add_and_subtract(num2=2,num1=10)
print("The sum is =", add)
print("The difference is =",diff)

The sum is = 12
The difference is = 8


In [15]:
#return kelimesinden sonraki kodlar çalıştırılmaz

In [16]:
def add_sum_diff(func,num1,num2):
    x,y=func(num1,num2)
    return x+y

In [18]:
val=add_sum_diff(add_and_subtract,10,3)
print(val)
#10+3 = 13 
#10-3=7
#13+7=20

20


In [21]:
def add_numbers(*args):
    for i in args:
        print(i)
        
add_numbers(1,2,3,4,5)

1
2
3
4
5


In [22]:
def add_numbers(**kwargs):
    for key in kwargs:
        print("another keyword arg: {}: {}".format(key, kwargs[key]))
        
add_numbers(num1=1,num2=2,num3=3,num4=4,num5=5)

another keyword arg: num1: 1
another keyword arg: num2: 2
another keyword arg: num3: 3
another keyword arg: num4: 4
another keyword arg: num5: 5


In [23]:
#Python Modules

In [24]:
import random

for i in range(6):
    value=random.randint(1,8)
    print(value)

4
2
3
3
6
4


In [26]:
from random import randint

for i in range(6):
    value=randint(1,8)
    print(value)

1
8
6
6
2
7


In [27]:
from random import randint as my_rand_func

for i in range(6):
    value=my_rand_func(1,8)
    print(value)

8
5
8
3
7
7


In [31]:
!pip install google-api-python-client

In [29]:
#Python Exceptions

In [32]:
num1=4
num2=0
#print(num1/num2)  hata verecek o yüzden kapalı
#print("Exiting")

In [33]:
#ImportError
#IndexError   out of range
#SyntaxError  
#TypeError    fonksiyon yanlış tip variable ile çağrılırsa
#ValueError  istenen değerle çağrılmazsa bu uyarı gelir

In [ ]:
#import nump1  
#list=[1,2,3]  list[4]
#liste={1,2,3]
#x=int('One')
#def add_num(num1,num2):
#    return int(num1)+int(num2)  #value error
#add_num("One","Two")

In [35]:
try:
    num1=8
    num2=4  #0 yaparsak excepte gider
    x=num1/num2
    print("This statement will not be printed")
except ZeroDivisionError:
    print("Zero Division Error")

This statement will not be printed


In [36]:
try:
    variable=10
    print(variable+"Hello")
    print(variable/2)
    
except ZeroDivisionError:
    print("Divided by Zero")
except(ValueError,TypeError):
    print("Error Occured")

Error Occured


In [37]:
try:
    4/0
except:
    print("Error Occured")

Error Occured


In [38]:
try:
    print("Step 1")
    4/0    
except ZeroDivisionError:
    print("Divided by Zero")

finally:
    print("This will be always executed")

Step 1
Divided by Zero
This will be always executed


In [42]:
try:
    print(8/0)    
except ZeroDivisionError:
    print()#print(unknown_data) geniş hata bunu açınca olur 
    #print() boşluk oluşsun diye ekledim
finally:
    print("This will be always executed")


This will be always executed


In [44]:
print("data1")
#raise ValueError #kod açılınca ValueError görünür
print("2")

data1
2


In [46]:
name="123"
#raise NameError("Invalid Name") #kod açılınca ValueError görünür

In [49]:
"""try:
    num=5/0
except:
    print("Error occured")
    raise
""" #kod açılınca division by zero görünür

'try:\n    num=5/0\nexcept:\n    print("Error occured")\n    raise\n'

In [51]:
def my_func():
    try:
        4/0  #ZeroDivisionError fırlatır
    except Exception as ex:
        template="An exception of type {0} occured. Arguments:\n{1!r}"
        message=template.format(type(ex).__name__,ex.args)
        print(message)
        raise # The ZeroDivisionError is propogated out
        
def another_func():
    try:
        my_func()
    except ZeroDivisionError: #The ZeroDivisionError is caught
        print('Error')
        
another_func()

An exception of type ZeroDivisionError occured. Arguments:
('division by zero',)
Error


In [52]:
#File Handling 

In [2]:
my_file = open("philosphers.txt","w")

In [3]:
lines=['The great philosphers of the world\n','John Locke\n','Kant\n']
my_file.writelines(lines)
my_file.close()

In [4]:
my_file=open("philosphers.txt","r")
file_data=my_file.read()
print(file_data)
my_file.close()

The great philosphers of the world
John Locke
Kant



In [5]:
my_file=open("philosphers.txt","w")
my_file.write("John Locke\n")
my_file.close()
#üstüne yazdı eskisini sildi

In [6]:
my_file=open("philosphers.txt","r")
file_data=my_file.read()
print(file_data)
my_file.close()

John Locke



In [7]:
my_file=open("philosphers.txt","a")
my_file.write("Immanuel Kant\n")
my_file.close()

In [8]:
my_file=open("philosphers.txt","r")
file_data=my_file.read()
print(file_data)
my_file.close()

John Locke
Immanuel Kant



In [10]:
try:
    my_file=open("philosphers.txt","w")
    my_file.write("The great philosphers of the world")
finally:
    my_file.close()

In [11]:
with open("philosphers.txt") as f:
    print(f.read())

The great philosphers of the world


In [12]:
x=(None==None)
print(x)

True


In [13]:
x=(None==True)
print(x)

False


In [14]:
x=(None==False)
print(x)

False


In [15]:
def afunc():
    print("Hello")

In [16]:
print(afunc())

Hello
None


In [17]:
#Dictionaries

In [18]:
philosphers={"UK":"Russell","Germany":"Karl Marx"}
print(philosphers["UK"])

Russell


In [19]:
print(philosphers["Germany"])

Karl Marx


In [20]:
#philosphers["India"] hata döndürür keyerror

In [22]:
#d={[1,2,3,]:"One Two Three"}
#print(d) type hatası verir

In [23]:
philosphers={"UK":"Russell","Germany":"Karl Marx","India":"None"}
philosphers["India"]="AryaBhatt"
philosphers["UK"]="John Stuart Mill"
philosphers["USA"]="John Dewey"

print(philosphers)

{'UK': 'John Stuart Mill', 'Germany': 'Karl Marx', 'India': 'AryaBhatt', 'USA': 'John Dewey'}


In [28]:
philosphers={"UK":"Russell","Germany":"Karl Marx","India":"Arya Bhatt"}
print("India" in philosphers)
print("Brazil" in philosphers)
print("Brazil" not in philosphers)

True
False
True


In [30]:
philosphers={"UK":"Russell","Germany":"Karl Marx","India":"Arya Bhatt"}
print(philosphers.get("Russia","No philospher set for Russia"))
print(philosphers.get("Russia"))
#print(philosphers["Russia"]) #keyerror verir

No philospher set for Russia
None


In [31]:
#Tuples

In [32]:
philosphers=("Russell","Karl Marx","Arya Bhatt")
print(philosphers[0])

Russell


In [34]:
#philosphers[0]="John Locke" #atama yapılamaz

In [35]:
def multiple_ret_params():
    return 1,2,3

In [36]:
x=multiple_ret_params()
print(type(x))

<class 'tuple'>


In [37]:
def func(*arg):
    print("The argument type is", type(arg))
    pass

In [38]:
func(1,2,3)

The argument type is <class 'tuple'>


In [39]:
#PArantezsiz de oluşturulabilir
philosphers="Russell","Karl Marx","Arya Bhatt"
print(philosphers[2])

Arya Bhatt


In [44]:
#List Slices
squared=[0,1,4,9,16,25,36,49,64,81]
print(squared[2:6])
print(squared[0:1])

[4, 9, 16, 25]
[0]


In [45]:
print(squared[::2])

[0, 4, 16, 36, 64]


In [46]:
print(squared[2:8:3])

[4, 25]


In [47]:
print(squared[1:-1])

[1, 4, 9, 16, 25, 36, 49, 64]


In [48]:
print(squared[:-1])

[0, 1, 4, 9, 16, 25, 36, 49, 64]


In [49]:
print(squared[:-1:2])

[0, 4, 16, 36, 64]


In [50]:
#List comprehensions

In [53]:
square=[a*a for a in range(5)]
print(square)

[0, 1, 4, 9, 16]


In [54]:
square=[a*a for a in range(5) if a%3==0]
print(square)

[0, 9]


In [55]:
#String Functions

In [56]:
nums=[1,2,3]
out="The numbers are {},{},{}".format(nums[0],nums[1],nums[2])
print(out)

The numbers are 1,2,3


In [57]:
out="The numbers are {a},{b},{c}".format(b=nums[1],a=nums[0],c=nums[2])
print(out)

The numbers are 1,2,3


In [58]:
str=",".join(["Life", "is", "good"])
print(str)

Life,is,good


In [59]:
str="Life", "is", "good".replace("good","strange")
print(str)

('Life', 'is', 'strange')


In [60]:
str="Hello World. Hello Python".replace("Hello","Namaste")
print(str)

Namaste World. Namaste Python


In [63]:
bool="Hello World. Hello Python".startswith("Hello")
print(bool)

True


In [65]:
bool="Hello World. Hello Python".endswith("Python")
print(bool)

True


In [66]:
upper="hello world".upper()
print(upper)

HELLO WORLD


In [67]:
lower="HELLO world".lower()
print(lower)

hello world


In [68]:
list="Lion,Tiger,Elephant".split(",")
print(list)

['Lion', 'Tiger', 'Elephant']


In [69]:
list[1]

'Tiger'

In [70]:
#Numeric Functions

In [72]:
list=[1,4,6,7]
print(min(list))
print(max(list))
print(sum(list))
print(abs(-10))

1
7
18
10


In [73]:
#List Functions

In [74]:
l=[22,33,45,67,54]
print(any(l))

True


In [75]:
l=[0]
print(any(l))

False


In [76]:
l=[-1]
print(any(l))

True


In [77]:
l=[0,False]
print(any(l))

False


In [78]:
l=[0,False,5]
print(any(l))

True


In [79]:
l=[]
print(any(l))

False


In [81]:
l=[22,33,45,67,54]
print([i>30 for i in l])

[False, True, True, True, True]


In [82]:
any([i>30 for i in l])

True

In [83]:
s="This is good"
print(any(s))

True


In [84]:
s="000"
print(any(s))

True


In [85]:
s=''
print(any(s))

False


In [86]:
#Any with dictionaries

In [87]:
d={0:"False"}
print(any(d))

False


In [89]:
d={0:"False",1:"True"}
print(any(d))

True


In [90]:
d={0:"False",False:0}
print(any(d))

False


In [91]:
d={}
print(any(d))

False


In [92]:
d={"0":"False"}
print(any(d))

True


In [93]:
#All function

In [94]:
l=[1,3,4,5]
print(all(l))

True


In [95]:
l=[0,False]
print(all(l))

False


In [96]:
l=[1,3,4,0]
print(all(l))

False


In [97]:
l=[0,False,5]
print(all(l))

False


In [98]:
l=[]
print(all(l))

True


In [99]:
s="This is good"
print(all(s))

True


In [100]:
s='000'
print(all(s))

True


In [101]:
s=''
print(all(s))

True


In [106]:
d={0:"False",1:"False"}
print(all(d))

False


In [102]:
d={1:"True",2:"True"}
print(all(d))

True


In [103]:
d={1:"True",False:0}
print(all(d))

False


In [104]:
d={}
print(all(d))

True


In [105]:
d={'0':"True"}
print(all(d))

True


In [107]:
#enumerate function
nums=[4,8,12,16]
for t in enumerate(nums):
    print(t)

(0, 4)
(1, 8)
(2, 12)
(3, 16)


In [110]:
t[0],t[1]

(3, 16)

In [111]:
#OOP Object Oriented Programming

In [112]:
#Class oluşturalım bu class 2 özelliğe sahip name ve country

In [114]:
class Philospher:
    
    def __init__(self,name,country):
        self.name=name
        self.country=country
        
russell=Philospher("Russell","UK")
print(russell.name,russell.country)

Russell UK


In [115]:
panini=Philospher("Panini","India")
print(panini.name,panini.country)

Panini India


In [119]:
#Methods and Class Level Attributes

In [121]:
class Philospher:
    
    def __init__(self,name,country):   #Bu constructordır
        self.name=name
        self.country=country
        
    def show_details(self):
        print("name = {},country={}".format(self.name,self.country))
        
russell=Philospher("Russell","UK")
russell.show_details()

name = Russell,country=UK


In [3]:
class Philospher:
    count=0
    
    def __init__(self,name,country):   #Bu constructordır
        self.name=name
        self.country=country
        Philospher.count=Philospher.count+1 #class level attr artıyor
        
    def show_details(self):
        print("name = {},country={}".format(self.name,self.country))
        
russell=Philospher("Russell","UK")
panini =Philospher('Panini','India')

In [4]:
print("The Philospher count is ",Philospher.count)

The Philospher count is  2


In [5]:
print("The Philospher count is ",russell.count)

The Philospher count is  2


In [6]:
print("The Philospher count is ",panini.count)

The Philospher count is  2


In [7]:
class Philospher:
    count=0
    
    def __init__(self,name,country):   #Bu constructordır
        self.name=name
        self.country=country
        Philospher.count=Philospher.count+1 #class level attr artıyor
        
    def show_details(self):
        print("name = {},country={}".format(self.name,self.country))
        
russell=Philospher("Russell","UK")
#russell.town #bunu çalıştırınca attribute error verir

In [8]:
#Inheritance

In [9]:
class Philospher:
    count=0
    
    def __init__(self,name,country):   #Bu constructordır
        self.name=name
        self.country=country
        Philospher.count=Philospher.count+1 #class level attr artıyor
    
    def show_details(self):
        print("name = {},country={}".format(self.name,self.country))
        
class GreekPhilospher(Philospher):
    def __init__(self,name,country,details):   #Bu constructordır
        Philospher.__init__(self,name,country)  #base class constructor oluşturuldu
        self.details=details
    
    def show_details(self):
        print("name = {},country={},philosophy={} ".format(self.name,self.country,self.details))
        
plato=GreekPhilospher("Plato","Greece","After Death Philosophy")
plato.show_details()

name = Plato,country=Greece,philosophy=After Death Philosophy 


In [10]:
#Super parent class function çağırmak için kullanılabilir
class Philospher:
    count=0
    
    def __init__(self,name,country):   #Bu constructordır
        self.name=name
        self.country=country
        Philospher.count=Philospher.count+1 #class level attr artıyor
    
    def show_details(self):
        print("name = {},country={}".format(self.name,self.country))
        
class GreekPhilospher(Philospher):
    def __init__(self,name,country,details):   #Bu constructordır
        Philospher.__init__(self,name,country)  #base class constructor oluşturuldu
        self.details=details
    
    def show_details(self):
        super().show_details()  #Parenttaki show detaili çağırır
        print("The special philosophy is {}".format(self.details))
        
plato=GreekPhilospher("Plato","Greece","After Death Philosophy")
plato.show_details()

name = Plato,country=Greece
The special philosophy is After Death Philosophy


In [12]:
#Magic Methods
class MegaNumber:
    def __init__(self,x,y):
        self.x=x
        self.y=y
        
    def __add__(self,othermeganumber):
        return MegaNumber(self.x+othermeganumber.x,self.y+othermeganumber.y)


first=MegaNumber(10,12)
second=MegaNumber(20,40)
third=first+second
print(third.x,third.y)


30 52


In [13]:
#Python Object LifeCycle

class Philospher:
        
    def __init__(self,name,country):   #Bu constructordır
        self.name=name
        self.country=country
        print("Inside Constructor")
    
    def __new__(cls,*args,**kwargs):
        print("Executing __new__")
        instance=super(Philospher,cls).__new__(cls)
        return instance
    
russell=Philospher("Russell","UK")
print(russell.name,russell.country)
        

Executing __new__
Inside Constructor
Russell UK


In [14]:
#Garbage Collection
b=90
print(b)

90


In [15]:
c=b
print(c)

90


In [16]:
d=[b]
print(d)

[90]


In [17]:
del b

In [18]:
print(c)

90


In [19]:
print(d)

[90]


In [20]:
c=80
d[0]=-1

In [25]:
#Object data hiding , weak method private method

class Philospher:
        
    def __init__(self,name,country):   #Bu constructordır
        self._name=name
        self._country=country
    
    def __repr__(self):
        str="Name={}, Country={}".format(self._name,self._country)
        return str
    
russell=Philospher("Russell","UK")
print(russell)
print(russell._name,russell._country)
        

Name=Russell, Country=UK
Russell UK


In [31]:
class Philospher:
        
    def __init__(self,name,country):   #Bu constructordır
        self.__name=name   #çift altçizgi underscore var
        self.__country=country
    
    def __repr__(self):
        str="Name={}, Country={}".format(self.__name,self.__country)
        return str
    
russell=Philospher("Russell","UK")
print(russell._Philospher__name)
#print(russell.__name)  #dışarıdan ulaşılamaz

Russell


In [32]:
#Classic and static methods

class Philospher:
    count=0
    
    def __init__(self,name,country):   #Bu constructordır
        self.name=name
        self.country=country
        Philospher.count=Philospher.count+1 #class level attr artıyor
    
    @classmethod
    def show_count(cls):
        print("The number of philosphers are {}".format(cls.count))

    def print_in_fancy_style(philospher):  #static method
        print("******** The philosphers name is {} ***".format(philosphers.name))
   
    def show_count_static():
        print("The number of philosphers are {}".format(count))


In [33]:
#Numpy

In [1]:
import numpy as np

In [2]:
a=np.array([100,200,300])
print(type(a))
print(a.shape)
print(a.ndim)

<class 'numpy.ndarray'>
(3,)
1


In [3]:
print(a[0],a[1],a[2])

100 200 300


In [4]:
a[0]=500
print(a)

[500 200 300]


In [5]:
b=np.array([[1,2,3],[4,5,6]])
print(b.shape)
print(b.ndim)
print(b[0,0],b[0,1],b[1,0])

(2, 3)
2
1 2 4


In [ ]:
#Scalar 42 değeri 0D arraydir
#[41,pi,pow(2,0.5)]  1D arraydir
#[[41,pi,3],
#[1,2,3],
#[10,20,30]]  2D arraydir


In [6]:
#Add Subtract Multiply
x=np.array([[1,2],[3,4]],dtype=np.float64)
y=np.array([[5,6],[7,8]],dtype=np.float64)

In [7]:
print(x+y)

[[ 6.  8.]
 [10. 12.]]


In [8]:
print(np.add(x,y))

[[ 6.  8.]
 [10. 12.]]


In [9]:
print(x-y)

[[-4. -4.]
 [-4. -4.]]


In [10]:
print(np.subtract(x,y))

[[-4. -4.]
 [-4. -4.]]


In [11]:
print(x*y)

[[ 5. 12.]
 [21. 32.]]


In [12]:
print(np.multiply(x,y))

[[ 5. 12.]
 [21. 32.]]


In [13]:
print(x/y)

[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [14]:
print(np.divide(x,y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [15]:
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


In [16]:
#Numpy Dot Product

In [17]:
x=np.array([[1,2],[3,4]])
y=np.array([[5,6],[7,8]])

v=np.array([9,10])
w=np.array([11,12])

In [18]:
print(v.dot(w))

219


In [19]:
print(np.dot(v,w))

219


In [21]:
print(x.dot(v))

[29 67]


In [22]:
print(np.dot(x,v))

[29 67]


In [23]:
print(x.dot(y))

[[19 22]
 [43 50]]


In [24]:
print(np.dot(x,y))

[[19 22]
 [43 50]]


In [25]:
#Slicing

In [26]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [28]:
b=a[:2,1:3]
print(b,'\n')

[[2 3]
 [6 7]] 



In [29]:
print(a[0,1])

2


In [30]:
b[0,0]=77
print(a[0,1],'\n')

77 



In [31]:
print(b,'\n')

[[77  3]
 [ 6  7]] 



In [32]:
print(a,'\n')

[[ 1 77  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 



In [33]:
#Indexing and Slicing

In [34]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [35]:
row_r1=a[1,:]
row_r2=a[1:2,:]
print(row_r1,row_r1.shape)
print(row_r2,row_r2.shape)

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)


In [36]:
col_r1=a[:,1]
col_r2=a[:,1:2]
print(col_r1,col_r1.shape)
print(col_r2,col_r2.shape)

[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


In [37]:
#Array Indexing

In [38]:
a=np.array([[1,2],[3,4],[5,6]])

In [39]:
print(a[[0,1,2],[0,1,0]])
#0,1,2 hepsini ver sonra 1,4,5i ver diyoruz

[1 4 5]


In [42]:
print(np.array([a[0,0],a[1,1],a[2,0]]))

[1 4 5]


In [43]:
print(a[[0,0],[1,1]])

[2 2]


In [44]:
print(np.array([a[0,1],a[0,1]]))

[2 2]


In [46]:
a=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [47]:
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [48]:
print(a.shape)

(4, 3)


In [49]:
b=np.array([0,2,0,1])

In [51]:
print(a[np.arange(4),b])
#([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
#  0            2   0           1       1,6,7,11

[ 1  6  7 11]


In [52]:
a[np.arange(4),b]+=10
print(a)

[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


In [55]:
#Boolean Array Indexing

In [61]:
a=np.array([[1,2],[3,4],[5,6]])

In [62]:
bool_idx=(a>2)

In [63]:
print(bool_idx)

[[False False]
 [ True  True]
 [ True  True]]


In [64]:
#Numpy Sum
x=np.array([[1,2],[3,4]])

In [65]:
print(np.sum(x))
print(np.sum(x,axis=0))
print(np.sum(x,axis=1))

10
[4 6]
[3 7]


In [66]:
#Reshape

In [71]:
array=np.arange(8)
print('Original array: \n',array)

Original array: 
 [0 1 2 3 4 5 6 7]


In [72]:
array=np.arange(4).reshape(2,2)
print(' array: \n',array)

 array: 
 [[0 1]
 [2 3]]


In [73]:
array=np.arange(8).reshape(4,2)
print(' array: \n',array)

 array: 
 [[0 1]
 [2 3]
 [4 5]
 [6 7]]


In [74]:
array=np.arange(8).reshape(2,2,2)
print(' array: \n',array)

 array: 
 [[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [77]:
from numpy import array
data = [[11,22],
       [33,44],
       [55,66]]
data=array(data)
print("rows: ",data.shape[0])
print("columns: ",data.shape[1])

rows:  3
columns:  2


In [78]:
#reshape 1D array to 2D array
from numpy import array
from numpy import reshape
data=array([11,22,33,44,55])
print(data.shape)

(5,)


In [79]:
#reshape
print(data.shape[0])
data=data.reshape((data.shape[0],1))
print(data.shape)

5
(5, 1)


In [80]:
print(data)

[[11]
 [22]
 [33]
 [44]
 [55]]


In [81]:
#Numpy Tensors 1D, 2D, 3D

In [82]:
#Tensor 1 sayı içeriyorsa scalar olarak adlandırılır 0D Tensor
x=np.array(12)
print(x.ndim)

0


In [83]:
#Sayılardan oluşan array vector olarak adlandırılır 1D Tensordur
a=np.array([100,200,300])
print(a.ndim)

1


In [84]:
#Matrisler 2D tensorlardır. Vector arrayleri matrixtir
#2 axesi vardor rows and columns
x=np.array([[5,78,2,34,0],
           [6,79,3,35,1],
           [7,80,4,36,2]])
print(x.ndim)

2


In [85]:
#3D tensor
x=np.array([[[5,78,2,34,0],
           [6,79,3,35,1],
           [7,80,4,36,2]],
            [[5,78,2,34,0],
            [6,79,3,35,1],
           [7,80,4,36,2]],
            [[5,78,2,34,0],
            [6,79,3,35,1],
           [7,80,4,36,2]]] )
print(x)
print(x.ndim)

[[[ 5 78  2 34  0]
  [ 6 79  3 35  1]
  [ 7 80  4 36  2]]

 [[ 5 78  2 34  0]
  [ 6 79  3 35  1]
  [ 7 80  4 36  2]]

 [[ 5 78  2 34  0]
  [ 6 79  3 35  1]
  [ 7 80  4 36  2]]]
3


In [86]:
#Deep Learningte 0D'den 4D'ye tensorları manipule edeceğiz

In [87]:
from keras.datasets import mnist
(train_images,train_labels),(test_images,test_labels)=mnist.load_data()
print(train_images.ndim)
print(train_images.shape)
print(train_images.dtype)

11501568/11490434 [==============================] - 5s 0us/step
3
(60000, 28, 28)
uint8


In [88]:
#Vector data 2D tensors of shape (samples,features)
#Timeseries data or sequence data 3D tensors of shape (samples,timesteps, features)
#Images 4D tensors of shape (samples,height,width,channels) or (samples,channels,height,width)
#Video 5D tensors of shape (samples, frames, height, width, channels)

In [89]:
#Transposing

In [90]:
x=np.array([[1,2],[3,4]])
print(x)

[[1 2]
 [3 4]]


In [91]:
print(x.T)

[[1 3]
 [2 4]]


In [92]:
v=np.array([1,2,3])
print(v)
print(v.T)

[1 2 3]
[1 2 3]


In [93]:
#Numpy Broadcasting

x=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
v=np.array([1,0,1])
y=np.empty_like(x)
print(y)

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


In [94]:
for i in range(4):
    y[i,:]=x[i,:]+v

print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [95]:
x=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
v=np.array([1,0,1])
y=x+v
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [96]:
#Pandas

In [98]:
import numpy as np
import pandas as pd

In [99]:
a=np.array([1,2,3,4])
series=pd.Series([1,2,3,4])
print(series.describe(),'\n')

count    4.000000
mean     2.500000
std      1.290994
min      1.000000
25%      1.750000
50%      2.500000
75%      3.250000
max      4.000000
dtype: float64 



In [100]:
series=pd.Series([1,2,3,4])
print(series[0],'\n')
print(series[:2],'\n')

1 

0    1
1    2
dtype: int64 



In [103]:
series=pd.Series([1,2,3,4])
for d in series:
    print(d)

1
2
3
4


In [104]:
series=pd.Series([1,2,3,4])
print('mean',series.mean())
print('std',series.std())
print('max',series.max())

mean 2.5
std 1.2909944487358056
max 4


In [105]:
a=pd.Series([1,2,3,4])
b=pd.Series([1,2,1,2])
print(a+b)
print(a*2)
print(a>=3)
print(a[a>=3])

0    2
1    4
2    4
3    6
dtype: int64
0    2
1    4
2    6
3    8
dtype: int64
0    False
1    False
2     True
3     True
dtype: bool
2    3
3    4
dtype: int64


In [106]:
#Panda Series Index

population = pd.Series([1415045928,1354051854,326766748],index=["China","India","USA"])
print(population,'\n')


China    1415045928
India    1354051854
USA       326766748
dtype: int64 



In [110]:
print('Population[0]=',population[0],'\n')
print('Population[\'India\']=',population['India'])

Population[0]= 1415045928 

Population['India']= 1354051854


In [112]:
#Aynı işlemleri numpy array ile yapsaydık 2 array oluşturmak
#zorunda kalacaktık

population = np.array([1415045928,1354051854,326766748])
index=np.array(["China","India","USA"])
print(population,'\n')
print('Population of {} is {}'.format(index[1],population[1]))


[1415045928 1354051854  326766748] 

Population of India is 1354051854


In [115]:
#Pandas Loc and iloc

population = pd.Series([1415045928,1354051854,326766748],index=["China","India","USA"])
print(population[0])
print(population.iloc[0])
print(population.loc['China'])

1415045928
1415045928
1415045928


In [116]:
#Finding Max

population = pd.Series([1415045928,1354051854,326766748],index=["China","India","USA"])
print('Country with maximum population = ',population.values.argmax())
print("The max population is of country = {} and population = {}".format(index[population.values.argmax()],
                                                                        population.iloc[population.values.argmax()]))

Country with maximum population =  0
The max population is of country = China and population = 1415045928


In [118]:
#Pandas series Addition

#Addition when indexes are the same
s1=pd.Series([1,2,3,4],index=['a','b','c','d'])
s2=pd.Series([100,200,300,400],index=['a','b','c','d'])
print(s1+s2)

a    101
b    202
c    303
d    404
dtype: int64


In [119]:
#Indexler aynı element değillerse
s1=pd.Series([1,2,3,4],index=['a','b','c','d'])
s2=pd.Series([100,200,300,400],index=['c','d','e','f'])
print(s1+s2)

a      NaN
b      NaN
c    103.0
d    204.0
e      NaN
f      NaN
dtype: float64


In [120]:
s1=pd.Series([1,2,3,4],index=['a','b','c','d'])
s2=pd.Series([100,200,300,400],index=['e','f','g','h'])
print(s1+s2)

a   NaN
b   NaN
c   NaN
d   NaN
e   NaN
f   NaN
g   NaN
h   NaN
dtype: float64


In [121]:
#dropna kullanımı
s1=pd.Series([1,2,3,4],index=['a','b','c','d'])
s2=pd.Series([10,20,30,40],index=['a','b','g','h'])
result=s1+s2
print(result)
print(result.dropna())

a    11.0
b    22.0
c     NaN
d     NaN
g     NaN
h     NaN
dtype: float64
a    11.0
b    22.0
dtype: float64


In [122]:
s1=pd.Series([1,2,3,4],index=['a','b','c','d'])
s2=pd.Series([10,20,30,40],index=['a','b','g','h'])
result=s1.add(s2,fill_value=0)
print(result.dropna())

a    11.0
b    22.0
c     3.0
d     4.0
g    30.0
h    40.0
dtype: float64


In [123]:
#Pandas Apply kullanımı
def make_capital(str):
    return str.capitalize()

s1=pd.Series(['india','china','brazil'],index=['a','b','c'])
s2=s1.apply(make_capital)
print(s2)

a     India
b     China
c    Brazil
dtype: object


In [124]:
#Dataframe Introduction
#2 boyutlu arraydir
country_df=pd.DataFrame({
    'country':['India','China','USA'],
    'population':[1415045928,1354051854,326766748],
    'capital':['Delhi','Bejing','WDC']
})

print(country_df)
print(country_df.mean())

  country  population capital
0   India  1415045928   Delhi
1   China  1354051854  Bejing
2     USA   326766748     WDC
population    1.031955e+09
dtype: float64


C:\Users\Bootcamp\Anaconda3\lib\site-packages\ipykernel_launcher.py:10: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  # Remove the CWD from sys.path while we load stuff.


In [125]:
#Pandas Datagrame Index , Loc , iloc

country_df=pd.DataFrame({
    'population':[1415045928,1354051854,326766748],
    'capital':['Delhi','Bejing','WDC'],
     'gdp':[2848231,14092514,20412870]
},
index=['India','China','USA'],)

print(country_df)
print(country_df.loc['India'])
print(country_df.iloc[0])
#Data frameler collection of series olarak da tanımlanabilir

       population capital       gdp
India  1415045928   Delhi   2848231
China  1354051854  Bejing  14092514
USA     326766748     WDC  20412870
population    1415045928
capital            Delhi
gdp              2848231
Name: India, dtype: object
population    1415045928
capital            Delhi
gdp              2848231
Name: India, dtype: object


In [126]:
#Pandas Sum along axis

country_df=pd.DataFrame({
    'population':[1415045928,1354051854,326766748],
    'capital':['Delhi','Bejing','WDC'],
     'gdp':[2848231,14092514,20412870]
},
index=['India','China','USA'],)

print(country_df.values)


[[1415045928 'Delhi' 2848231]
 [1354051854 'Bejing' 14092514]
 [326766748 'WDC' 20412870]]


In [130]:
df=pd.DataFrame({'A':[0,1,2],'B':[3,4,5]})
print(df)
print()
print(df.sum())
print()
print(df.sum(axis=0),'\n')
print(df.sum(axis=1),'\n')

   A  B
0  0  3
1  1  4
2  2  5

A     3
B    12
dtype: int64

A     3
B    12
dtype: int64 

0    3
1    5
2    7
dtype: int64 



In [131]:
#Pandas DataFrame Addition

df1=pd.DataFrame({'a':[1,2,3],'b':[4,5,6],'c':[7,8,9]})
df2=pd.DataFrame({'a':[10,20,30],'b':[40,50,60],'c':[70,80,90]})
print(df1+df2)

    a   b   c
0  11  44  77
1  22  55  88
2  33  66  99


In [132]:
df1=pd.DataFrame({'a':[1,2,3],'b':[4,5,6],'c':[7,8,9]})
df2=pd.DataFrame({'d':[10,20,30],'c':[40,50,60],'b':[70,80,90]})
print(df1+df2)

    a   b   c   d
0 NaN  74  47 NaN
1 NaN  85  58 NaN
2 NaN  96  69 NaN


In [134]:
df1=pd.DataFrame({'a':[1,2,3],'b':[4,5,6],'c':[7,8,9]},
                index=['row1','row2','row3'])
df2=pd.DataFrame({'a':[10,20,30],'b':[40,50,60],'c':[70,80,90]},
                index=['row4','row3','row2'])
print(df1+df2)

         a     b     c
row1   NaN   NaN   NaN
row2  32.0  65.0  98.0
row3  23.0  56.0  89.0
row4   NaN   NaN   NaN


In [135]:
#Pandas DataFrame ApplyMap

df= pd.DataFrame({
    'a':[1,2,3],
    'b':[10,20,30],
    'c':[5,10,15]
})

def add_one(x):
    return x+1

print(df.applymap(add_one))

   a   b   c
0  2  11   6
1  3  21  11
2  4  31  16


In [136]:
#Pandas Reading a CSV file
df=pd.read_csv('https://raw.githubusercontent.com/datasciencemastery/pandas-numpy-tutorial/master/data_sheet.csv',sep=',',error_bad_lines=False)
print(df,'\n')

C:\Users\Bootcamp\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3331: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version.


  exec(code_obj, self.user_global_ns, self.user_ns)


  itemcode           date  amount
0      MAG  01-April-2018    1000
1      MAG  02-April-2018     100
2      ALP  01-April-2018    1000
3      ALP  02-April-2018    1000 



In [138]:
print(df[df.itemcode=='MAG'],'\n')

  itemcode           date  amount
0      MAG  01-April-2018    1000
1      MAG  02-April-2018     100 



In [144]:
print((df.itemcode=='MAG') & (df.amount>100),'\n')

0     True
1    False
2    False
3    False
dtype: bool 



In [145]:
print(df[(df.itemcode=='MAG') & (df.amount>100)])

  itemcode           date  amount
0      MAG  01-April-2018    1000


In [ ]:
#bitti