# NumPy == Numerical Python
Python lists serve the purpose of arrays but they are slow to process.

Numpy has an array object that is 50 times faster than the traditional Python lists.

The array object in NumPy is called ndarray.

An array is a data structure that stores values of same data type while python list can contain element/values varied data types

Exercise by ABCD

In [ ]:
#https://www.udemy.com/course/learnpy-numpy/learn/lecture/25072968#overview

In [1]:
#Importing numpy library
#!pip install numpy
import numpy as np

In [2]:
a = [1,2 , 3, "a", "b"]
type(a)

list

In [3]:
a = [ 1,2]
a

[1, 2]

In [4]:
type(a)

list

In [5]:
a = [ 1,3]
a

[1, 3]

In [6]:
type(a)

list

In [7]:
#printing 10 floats of zeros(populate)
g = np.zeros(10)
g

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [8]:
g = np.zeros(10)
g

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
#3 rows/ arrays with 4 elements
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [20]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
#finding the type of array
type(g)

numpy.ndarray

In [13]:
#prints out 10 zero's with an element
g.shape= (10,1)
g

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [21]:
g.shape = (10,1)
g

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [12]:
#prints out the length
g.shape

(10,)

In [14]:
#printing elements in ones five times
k = np.ones(5)
k

array([1., 1., 1., 1., 1.])

In [23]:
k = np.ones(5)
k

array([1., 1., 1., 1., 1.])

In [15]:
#The type of k
type(k[1])

numpy.float64

In [16]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [21]:
l = np.empty(3)
l

array([1.28376621e-311, 0.00000000e+000, 4.94065646e-324])

In [24]:
l = np.empty(12)
l

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [14]:
###### Creating a one dimensional Array with a list
np.array([1,2,3])


array([1, 2, 3])

In [24]:
np.array([1,2,3])

array([1, 2, 3])

In [15]:
#making a list into an array
j = [1,2,3,3]
r = np.array([j])
r

array([[1, 2, 3, 3]])

In [26]:
j = [1,2,3,4]
r = np.array([j])
r

array([[1, 2, 3, 4]])

In [16]:
type(r)

numpy.ndarray

In [17]:
# storing in a Variable
a = np.array([1,2,3])
print(a)

[1 2 3]


In [19]:
# storing in a Variable with strings as an array
a = np.array(["A","B","C"])
print(a)

['A' 'B' 'C']


In [30]:
a = np.array(["a","b"])
print(a)

['a' 'b']


In [31]:
type(a)

numpy.ndarray

In [27]:
type(a)

numpy.ndarray

# Dimensions and operators exercise

In [33]:
#Checking the dimension of a
a= np.array([1,2,3])
print(a)
print(a.ndim)

[1 2 3]
1


In [33]:
a = np.array([1,2,3])
print(a)
print(a.ndim)

[1 2 3]
1


In [22]:
#Creating a 2 dimensional array
d = np.array([(1,2,3),(1,2,3)])
print(d)

[[1 2 3]
 [1 2 3]]


In [35]:
a = np.array([(1,3,3), (1,4,5)])
print(a)
print(a.ndim)

[[1 3 3]
 [1 4 5]]
2


In [10]:
#Check the dimentional type(2D)
z= np.array([(1,2,3),(2,3,5)])
print(z.ndim)

2


In [22]:
#Check the dimentional type(2D)
p= np.array([(1,2,3),(2,3,5)])
print(p.ndim)

2


In [12]:
#Check the dimentional type(3D)
z= np.array([[(1,2,3)],[(2,3,5)]])
print(z.ndim)

3


In [13]:
a = np.array([[(1,2,3)], [(2, 3, 4)]])
a
print(a.ndim)

3


In [14]:
z

array([[[1, 2, 3]],

       [[2, 3, 5]]])

In [23]:
p

array([[1, 2, 3],
       [2, 3, 5]])

In [16]:
#The question mark with the shift and tab key gives as documentation
?a

In [17]:
#The question mark with the shift and tab key gives as documentation of the particular parameter(shape)
?a.shape

In [24]:
#Check the dimentional type(3D)
p= np.array([[(1,2,3)],[(2,3,5)],[(2,3,5)]])
print(p.ndim)

3


In [25]:
p

array([[[1, 2, 3]],

       [[2, 3, 5]],

       [[2, 3, 5]]])

In [44]:
# the variable p is less than 5.prints a boolean
p < 4

array([[[ True,  True,  True]],

       [[ True,  True, False]],

       [[ True,  True, False]]])

In [45]:
# the variable p is greater than 2.prints a boolean
p > 3

array([[[False, False, False]],

       [[False, False,  True]],

       [[False, False,  True]]])

In [47]:
# the variable p is equal to 5.prints a boolean
p == 3

array([[[False, False,  True]],

       [[False,  True, False]],

       [[False,  True, False]]])

In [49]:
p

array([[[1, 2, 3]],

       [[2, 3, 5]],

       [[2, 3, 5]]])

In [48]:
# the variable p is not equal to 3.prints a boolean
p != 2

array([[[ True, False,  True]],

       [[False,  True,  True]],

       [[False,  True,  True]]])

In [26]:
#check the dimentional type( 1D)
y=np.array([1,2,3])
print(y.ndim)

1


# Byte, type and size

In [53]:
#check the byte size of each element
n=np.array([1,2,3])
print(n.itemsize)

4


In [59]:
m = np.array([1,2,3,4,5])
print(m.itemsize)

4


In [60]:
print(m.dtype)

int32


In [61]:
print(len(m))

5


In [54]:
print(n.dtype)

int32


In [55]:
print(len(n))

3


In [62]:
print(m.size)

5


In [40]:
#n = np.array([1,2,3], dtype = np.int8)
#n

In [41]:
#print(n.itemsize)

In [42]:
#check the datatype
q=np.array([1,2,3])
print(q.dtype)

int32


In [43]:
#Check the size/length of elements
w = np.array([1,2,3,4])
print(w.size)


4


# Range Arguments of np.arange()

This works with array with parameters; start, stop, and step. You have to pass at least one of the parameters.
the default value of step is 1 if no step value is provided

In [44]:
#This prints elements from 1 to 10 with steps of 3
np.arange(start=1, stop=10, step=3)

array([1, 4, 7])

In [45]:
np.arange(1, 10, 3)

array([1, 4, 7])

In [63]:
np.arange(1,20,4)

array([ 1,  5,  9, 13, 17])

In [46]:
# start at 10 and end at 30 with steps of 5
np.arange(10, 30, 5)

array([10, 15, 20, 25])

In [47]:
#counts from 0 to 9 
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [65]:
np.arange(0,13)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [66]:
np.arange(2,20,4)

array([ 2,  6, 10, 14, 18])

# Shape and reshaping
The shape of an array is the number of elements in each dimension.
The shape attribute returns a tuple

In [48]:
u = np.array([(1, 2, 3, 7), (5, 9, 7, 20)])

print(u.shape)

(2, 4)


In [69]:
m = np.array([(1,2,3), (2, 4, 5)])
m             
print(m.shape)

(2, 3)


In [72]:
m.ndim

2

In [70]:
#check the shape (arrays(2) and elements(3))
y=np.array([(1,2,4,5,6),(1,6,3,6,7)])
print(y.shape)

(2, 5)


In [71]:
y

array([[1, 2, 4, 5, 6],
       [1, 6, 3, 6, 7]])

In [51]:
y.ndim

2

In [52]:
#reshaping from 1-d to 2-d; 4 arrays with 3 elements
b = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

g = b.reshape(4, 3)
g

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [73]:
h = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
i = h.reshape(4,3)
i

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [53]:
#reshaping from 1-d to 3-d; 4 arrays with 3 elements
#k = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

#i = k.reshape(2, 3, 2)
#i

In [54]:
#converts to 1-d array
p = np.array([[1, 2, 3], [3, 5, 4]])

z= p.reshape(-1)
z

array([1, 2, 3, 3, 5, 4])

In [76]:
k = np.array([[1,2,3], [3,4,5]])
print(k.ravel())

[1 2 3 3 4 5]


In [55]:
#converts to 1-d array
p = np.array([(1, 2, 3), (3, 5, 4)])

z= p.reshape(-1)
z

array([1, 2, 3, 3, 5, 4])

In [56]:
#print all in a line
a=np.array([(1,2,3), (3,4,5)])
print(a.ravel())

[1 2 3 3 4 5]


In [57]:
#This prints elements from 0 - 11,four arrays with each array having 3 elements
b = np.arange(12).reshape(4, 3)     
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [77]:
c = np.arange(12).reshape(4,3)
print(c)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [58]:
#This prints elements from 0 - 14, three arrays with each array having 5 elements
a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [59]:
#reshaping; converting 2 rows and 4 elements into 4 rows, 2 elements

p = np.array([(1,2,3,5),(2,4,5,5)]) #Initial state 2rows:4 elements
print(p)

p= p.reshape(4,2)                    #converted to 4rows : 2 elements
print(p)

[[1 2 3 5]
 [2 4 5 5]]
[[1 2]
 [3 5]
 [2 4]
 [5 5]]


In [78]:
h = np.array([(1,2,3,5),(2,4,5,5)]) #Initial state 2rows:4 elements
print(h)

h = h.reshape(4,2)
h


[[1 2 3 5]
 [2 4 5 5]]


array([[1, 2],
       [3, 5],
       [2, 4],
       [5, 5]])

# Slicing
Slicing in python takes elements from a given index to another given index.

We pass slice == [start:end].

We can also   [start:end:step].


In [139]:
#this prints the element at the zeroeth index
n = np.array([1, 2, 3, 4, 19, 6, 7])

print(n[0])

1


In [140]:
m = np.array([1, 2, 3, 4, 19, 6, 7 ])
print(m[4])

19


In [51]:
#this prints out from the index position 1 to the 4th element excluding the 5th index element
n = np.array([1, 2, 3, 4, 19, 6, 7])

print(n[1:5])

[ 2  3  4 19]


In [141]:
m = np.array([1, 2, 3, 4, 19, 6, 7 ])
print(m[2:4])

[3 4]


In [53]:
#this prints out from the index position 0 to the 2nd element excluding the 2nd index element

n = np.array([1, 2, 3, 4, 19, 6, 7])

print(n[0:2])

[1 2]


In [18]:
#this prints all elements
n = np.array([1, 2, 3, 4, 19, 6, 7])

print(n[:])

[ 1  2  3  4 19  6  7]


In [142]:
m = np.array([1, 2, 3, 4, 19, 6, 7 ])
print(m[:])

[ 1  2  3  4 19  6  7]


In [52]:
#this prints out the last element
n = np.array([1, 2, 3, 4, 19, 6, 7])

print(n[-1])

7


In [144]:
m = np.array([1, 2, 3, 4, 19, 6, 8 ])
print(m[-1])

8


In [56]:
#this prints elements from the fourth to the end of the array
n = np.array([1, 2, 3, 4, 19, 6, 7])

print(n[4:])

[19  6  7]


In [145]:
m = np.array([1, 2, 3, 4, 19, 6, 7 ])
print(m[1:])

[ 2  3  4 19  6  7]


In [58]:
#this prints all elements from the zeroeth index to the 3rd element excluding the 4th index
n = np.array([1, 2, 3, 5, 19, 6, 7])

print(n[:4])

[1 2 3 5]


In [147]:
m = np.array([1, 2, 3, 4, 19, 6, 7 ])
print(m[:5])

[ 1  2  3  4 19]


In [59]:
#n = np.array([1, 2, 3, 5, 19, 6, 7])

#print(n[::4])

[ 1 19]


In [68]:
#from the second row/ array start at index 1 to 4
m = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(m[1, 1:4])

[7 8 9]


In [149]:
m = np.array([[1, 2, 3, 4, 5], [16, 72, 88, 9, 10]])
print(m[1, 0:3])

[16 72 88]


In [69]:
#from the first row/ array start at index 1 to 4
m = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(m[0, 1:4])

[2 3 4]


In [150]:
m = np.array([[1, 2, 3, 4, 5], [16, 72, 88, 9, 10]])
print(m[0, 0:3])

[1 2 3]


In [67]:
#Prints out the values from the both arrays from index position 1:4
m = np.array([[1, 2, 3, 4, 5], [6, 7, 6, 9, 12]])

print(m[0:2, 1:4])

[[2 3 4]
 [7 6 9]]


In [152]:
m = np.array([[1, 22, 33, 34, 5], [16, 72, 88, 9, 10]])
print(m[0:2,1:4])

[[22 33 34]
 [72 88  9]]


In [60]:
#slicing at index 2( selecting number 3 from the first array)
#the first array in the bracket is indexed as zero while the other is indexed as one
a = np.array([(1,2,3),(4,5,6)])
print(a[0,2])

3


In [157]:
m = np.array([[1, 2, 3, 4, 5], [16, 72, 88, 9, 10]])
print(m[0,4])

5


In [156]:
m = np.array([[1, 2, 3, 4, 5], [16, 72, 88, 9, 10]])
print(m[1,4])

10


In [43]:
#slicing at index 2( selecting number 6 from the second array)
#the first array in the brackets is indexed as zero while the other is indexed as one
a = np.array([(1,2,3),(4,5,6)])
print(a[1,2])

6


In [62]:
#printing the 3rd indexes of both arrays.
f= np.array([(1,2,3,4),(5,6,7,8)])

#this means all the rows(:) starting from the indexed row zero and print the third indexes
print(f[0:,3])

[4 8]


In [158]:
m = np.array([[1, 2, 3, 4, 5], [16, 72, 88, 9, 10]])
print(m[0:,3])

[4 9]


In [49]:
#printing the 3rd indexes of both arrays(Need to refresh on it).
#f= np.array([(1,2,3,4),(0,6,7,9),(0,6,7,8)])
#print(f[1:2,3])

[9]


# Slicing Images
python -m pip install -U pip
python -m pip install -U scikit-image  in your command line

You're using pip to install your packages ?

First install numpy : pip install numpy

Then install matplotlib pip install matplotlib

Then install scipy pip install scipy

And finally install skimage pip install scikit-image


In [27]:
!pip install scikit-image

In [10]:
#from skimage import io
#from skimage import io
#image = io.imread('meow.png')
#type(image)

ModuleNotFoundError: No module named 'skimage'

In [ ]:
#image.show

In [ ]:
#import matplotlib.pyplot as plt
#plt.imshow(image)

# Sum, max,min and linspace

In [80]:
#printing 5 values from 1-3( start at 1 and ends at 3 and populate with 5 elements)
a= np.linspace(1,3,5)
print(a)

[1.  1.5 2.  2.5 3. ]


In [81]:
a = np.linspace(2,6,4)
a

array([2.        , 3.33333333, 4.66666667, 6.        ])

In [65]:
#printing 5 values from 2-10
m= np.linspace(2,10,5)
print(m)

[ 2.  4.  6.  8. 10.]


In [66]:
#printing the max number in an array
z = np.array([1,2,30])
print(z.max())

30


In [82]:
m = np.array([1, 4, 10])
print(m.max())

10


In [83]:
print(m.min())

1


In [84]:
print(m.sum())

15


In [67]:
#printing the minimum number in an array
z = np.array([5,2,3])
print(z.min())

2


In [68]:
#printing the sum of numbers in an array
z = np.array([1,2,3])
print(z.sum())

6


# Random values

In [111]:
from numpy import random
#Generates random integer from 0-50
x = random.randint(50)

print(x)

10


In [115]:
m = random.randint(6)
m   

2

In [118]:
#Generates random float between 0 -1
x = random.rand()

print(x)

0.12109675218461002


In [121]:
m = random.rand()
m

0.8041464264582866

In [117]:
#Generate a 1-D array containing 10 random floats
x = random.rand(10)

print(x)

[0.81222217 0.66583087 0.14468225 0.73827699 0.72981617 0.59464537
 0.99688203 0.91053096 0.92924142 0.79201646]


In [122]:
m = random.rand(6)
m

array([0.39137699, 0.17652056, 0.10578553, 0.413938  , 0.71254117,
       0.55376669])

In [72]:
#Generates array with 3 rows, each row containing 4 random numbers
x = random.rand(3, 4)

print(x)

[[0.50492536 0.82877754 0.23744723 0.12567956]
 [0.16499598 0.39440997 0.16835039 0.99909266]
 [0.86968261 0.04201024 0.85463292 0.95898214]]


In [125]:
m = random.rand(5,3)
m

array([[0.20701868, 0.66074503, 0.8956998 ],
       [0.59785686, 0.91148845, 0.14818324],
       [0.44768798, 0.8773209 , 0.96087996],
       [0.46737398, 0.59874161, 0.72918685],
       [0.85768862, 0.08284344, 0.09160465]])

In [73]:
#Generates 10 random integers from 0 -100 ( 1d array)
x=random.randint(100, size=(10))

print(x)

[96 78 48 69  2 35 31 70  9 72]


In [74]:
(x.ndim)

1

In [127]:
m = random.randint(50, size= (20))
m

array([27, 18, 27, 29, 40, 15, 18, 12,  2, 15, 11, 49, 18, 19,  5, 45, 24,
       22, 45, 33])

In [129]:
print(m.ndim)

1


In [75]:
#This generates 10 random integers from 0 -100 with 3 rows ( 2d array)
x = random.randint(100, size=(3, 10))

print(x)

[[77 99 44 40 79 74  2 43 18 77]
 [17  2 45 76 46 32 17 76  1 29]
 [34 70 82 82 74  4 29 35 62 17]]


In [131]:
m = random.randint(50, size=(4,5))
m

array([[44, 13, 29, 37,  0],
       [22, 13, 39,  2, 12],
       [16, 15, 24, 34, 37],
       [23, 12, 11, 48, 34]])

In [133]:
#selects a value from a array
x = random.choice([7, 3, 10, 9])

print(x)

3


In [136]:
m = random.choice([6, 8, 9, 10])
m

6

In [77]:
#generates a 2d array with 3 rows and 4 elements in each row picking from the listed values in the list[3,5,7,9]
x = random.choice([3, 5, 7, 9], size=(3, 4))

print(x)

[[7 9 3 3]
 [7 5 7 9]
 [5 7 5 9]]


In [137]:
m = random.choice([4,5,6,7], size=(3,3))
m

array([[4, 4, 5],
       [7, 6, 5],
       [4, 6, 6]])

# AXES = AXIS 1 = ROWS AND AXIS 0 = COLUMNS

In [78]:
#this sums the rows
a = np.array([(1,2,3),(4,5,6)])
print(a.sum(axis=1))

[ 6 15]


In [79]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [106]:
m=np.array([(1,2,3), (3,4,5)])
m

array([[1, 2, 3],
       [3, 4, 5]])

In [107]:
print(m.sum(axis=1))

[ 6 12]


In [80]:
#this sums the columns
a=np.array([(1,2,3),(4,5,6)])
print(a.sum(axis=0))

[5 7 9]


In [108]:
m=np.array([(1,2,3), (3,4,5)])
m

array([[1, 2, 3],
       [3, 4, 5]])

In [109]:
print(m.sum(axis=0))

[4 6 8]


# Mathematical Functions- Addition, square root, standard deviation, etc

In [81]:
#this sums all elements 
a=np.array([(1,2,3),(4,5,6)])
print(a.sum())

21


In [94]:
m = np.array([(1,2,3),(4,5,8)])
print(m.sum())

23


In [95]:
m = np.array([(1,2,3),(4,5,8)])
print(np.sqrt(m))

[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.82842712]]


In [96]:
m = np.array([(1,2,3),(4,5,8)])
print(np.std(m))

2.266911751455907


In [82]:
#square root of each elements
a=np.array([(1,2,3),(4,5,6)])
print(np.sqrt(a))

[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]


In [83]:
#Standard deviation
a=np.array([(1,2,3),(4,5,6)])
print(np.std(a))

1.707825127659933


In [97]:
m = np.array([(1,2,3),(4,5,8)])
n = np.array([(1,2,6),(4,11,10)])
print(m+n)

[[ 2  4  9]
 [ 8 16 18]]


In [84]:
#Addition
a=np.array([(1,2,3),(4,5,6)])
b=np.array([(1,2,3), (1,2,3)])
print(a+b)

[[2 4 6]
 [5 7 9]]


In [85]:
#Subtraction
a=np.array([(1,2,3),(4,5,6)])
b=np.array([(1,2,3), (1,2,3)])
print(a-b)

[[0 0 0]
 [3 3 3]]


In [98]:
m = np.array([(1,2,3),(4,5,8)])
n = np.array([(1,2,6),(4,11,10)])
print(m-n)

[[ 0  0 -3]
 [ 0 -6 -2]]


In [86]:
#multiplication
a=np.array([(1,2,3),(4,5,6)])
b=np.array([(1,2,3), (1,2,3)])
print(a*b)

[[ 1  4  9]
 [ 4 10 18]]


In [99]:
m = np.array([(1,2,3),(4,5,8)])
n = np.array([(1,2,6),(4,11,10)])
print(m*n)

[[ 1  4 18]
 [16 55 80]]


In [100]:
m = np.array([(1,2,3),(4,5,8)])
n = np.array([(1,2,6),(4,11,10)])
print(m/n)

[[1.         1.         0.5       ]
 [1.         0.45454545 0.8       ]]


In [87]:
#Division
a=np.array([(1,2,3),(4,5,6)])
b=np.array([(1,2,3), (1,2,3)])
print(a/b)

[[1.  1.  1. ]
 [4.  2.5 2. ]]


In [55]:
#Multiply each element by 10
a=np.array([(1,2,3),(4,5,6)])
a*10

array([[10, 20, 30],
       [40, 50, 60]])

In [101]:
m = np.array([(1,2,3),(4,5,8)])
m*10


array([[10, 20, 30],
       [40, 50, 80]])

In [103]:
#exponentials
a=np.array([(1,2,3), (3,4,5)])
print(np.exp(a))

[[  2.71828183   7.3890561   20.08553692]
 [ 20.08553692  54.59815003 148.4131591 ]]


In [104]:
#log
a=np.array([(1,2,3), (3,4,5)])
print(np.log(a))

[[0.         0.69314718 1.09861229]
 [1.09861229 1.38629436 1.60943791]]


In [105]:
#log10
a=np.array([(1,2,3), (3,4,5)])
print(np.log10(a))

[[0.         0.30103    0.47712125]
 [0.47712125 0.60205999 0.69897   ]]


# Stacking

In [88]:
#Vertical Stacking
a=np.array([(1,2,3),(4,5,6)])
b=np.array([(1,2,3), (1,2,3)])
print(np.vstack((a,b)))

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [1 2 3]]


In [89]:
m = np.array([(1,2,3),(4,5,8)])
n = np.array([(1,2,6),(4,11,10)])
print(np.vstack((m,n)))

[[ 1  2  3]
 [ 4  5  8]
 [ 1  2  6]
 [ 4 11 10]]


In [90]:
m = np.array([(1,2,3),(4,5,8)])
n = np.array([(1,2,6),(4,11,10)])
print(np.vstack((n,m)))

[[ 1  2  6]
 [ 4 11 10]
 [ 1  2  3]
 [ 4  5  8]]


In [89]:
#Vertical Stacking
a=np.array([(1,2,3),(4,5,6)])
b=np.array([(1,2,3), (1,2,3)])
#change the position of the variables and we get a different stacking oreder
print(np.vstack((b,a)))

[[1 2 3]
 [1 2 3]
 [1 2 3]
 [4 5 6]]


In [90]:
#horizontal Stacking
a=np.array([(1,2,3),(4,5,6)])
b=np.array([(1,2,3), (1,2,3)])
print(np.hstack((a,b)))

[[1 2 3 1 2 3]
 [4 5 6 1 2 3]]


In [91]:
m = np.array([(1,2,3),(4,5,8)])
n = np.array([(1,2,6),(4,11,10)])
print(np.hstack((n,m)))

[[ 1  2  6  1  2  3]
 [ 4 11 10  4  5  8]]


In [ ]:
'''import matplotlib.pyplot as plt
x=np.arange(0,3*np.pi,0.1)
y=np.sin(x)
plt.plot(x,y)
plt.show()'''

In [ ]:
'''import matplotlib.pyplot as plt
x=np.arange(0,3*np.pi,0.1)
y=np.cos(x)
plt.plot(x,y)
plt.show()'''

In [ ]:
''''import matplotlib.pyplot as plt
x=np.arange(0,3*np.pi,0.1)
y=np.tan(x)
plt.plot(x,y)
plt.show()'''