In [1]:
#https://www.udemy.com/course/numpy-with-python/learn/lecture/17677106?start=15#overview

#3 saat

#NumPy+with+Python+-+DATAhill+Solutions.pdf indirildi
#DATA+SCIENCE+with+DA,+ML,+DL,+AI+using+Python+&++R.pdf indirildi

#Anaconda kullanıyor



In [2]:
import numpy as np
print(np.__version__)



1.21.6


In [6]:
a=[1,2,3,4,5]
print(a)
type(a)  
# [1,2,3,4,5]
b=np.array(a)
print(b) #  [1 2 3 4 5]
print(b+100)

[1, 2, 3, 4, 5]
[1 2 3 4 5]
[101 102 103 104 105]


In [7]:
b.shape # 5 verir 5 eleman var içinde
b.dtype #(int32) verir

dtype('int32')

In [10]:
a= np.array([1,2,3,4,5,6,7,8,9,10],ndmin=2)
print(a) #-->  [[1 2 3 4 5 6 7 8 9 10]]  verir
a.shape #(1,10) verir
a.dtype #int32 verir

[[ 1  2  3  4  5  6  7  8  9 10]]


dtype('int32')

In [12]:
a= np.array([1,2,3,4,5,6,7,8,9,10],dtype=complex)
#dersek dtype complex123 gelir
#ayrıca yanına +0j eklenir
print(a)


[ 1.+0.j  2.+0.j  3.+0.j  4.+0.j  5.+0.j  6.+0.j  7.+0.j  8.+0.j  9.+0.j
 10.+0.j]


In [13]:
a= np.array([[1,2,3],[4,5,6]])
print(a) # [[1 2 3] [4 5 6]]
a.shape # (2,3) verir

[[1 2 3]
 [4 5 6]]


(2, 3)

In [15]:
a= np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(a)  
a.shape # (2,2,3) verir



[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


(2, 2, 3)

In [17]:
a= np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(a)  
a.shape # (4,3) verir


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


(4, 3)

In [18]:
a= np.array([[1,2,3],[4,5,6]])
print(a)  #[[1 2 3] [4 5 6]]
a.shape =(3,2) #verirsek
a.shape #(3,2) verir
print(a) #[[1 2] [3 4] [5 6]] verir



[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [20]:
#Numpy Array devam:

a= np.array([[1,2,3],[4,5,6]])
print(a) # [[1 2 3] [4 5 6]]
a.reshape(3,2)
#ama a'ya bunu eşitlemezsek işlemez a yine 2,3 olarak devam eder
a=a.reshape(3,2)
print(a)



[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [21]:
print(a.ndim) #  dersek 2 döner 2 boyut var.

2


In [23]:
a= np.array([1,2,3,4,5,6])
print(a)
a=a.reshape(3,2)
print(a) # [[1 2] [3 4] [5 6]]
print(a.ndim)  #2



[1 2 3 4 5 6]
[[1 2]
 [3 4]
 [5 6]]
2


In [26]:
#np.empty(shape, dtype=float,order='C')  c row-major demektir
#bir de F var o da column-major order demektir
np.empty([3,2])  # 3*2lik çok küçük tesadüfi sayılardan oluşan
#array oluşturur
np.empty([3,2],dtype=int)
#array([[1,2],[3,4],[5,6]])# verir



array([[1, 2],
       [3, 4],
       [5, 6]])

In [28]:
np.zeros([3,2],dtype=int)
#array([[0,0],[0,0],[0,0]]) verir



array([[0, 0],
       [0, 0],
       [0, 0]])

In [29]:
np.ones([3,2],dtype=int)
#array([[1,1],[1,1],[1,1]]) verir



array([[1, 1],
       [1, 1],
       [1, 1]])

In [31]:
a=[1,2,3,4,5]
print(a)
type(a) #  [1,2,3,4,5]
b=np.asarray(a,dtype=int)
print(b) #  [1 2 3 4 5]



[1, 2, 3, 4, 5]
[1 2 3 4 5]


In [32]:
#np.arange(start,end,step) kullanımı
np.arange(5) #dersek array([0,1,2,3,4]) verir
print(np.arange(5)) #dersek [0 1 2 3 4] verir
print(np.arange(5,dtype=float)) #[0. 1. 2. 3. 4.] verir
print(np.arange(1,11)) #[1 2 3 4 5 6 7 8 9 10] döner
print(np.arange(1,11,2)) #[1 3 5 7 9] döner



[0 1 2 3 4]
[0. 1. 2. 3. 4.]
[ 1  2  3  4  5  6  7  8  9 10]
[1 3 5 7 9]


In [45]:
#linspace() kullanımı
print(np.linspace(1,11,2)) # [1. 11.] döner 
print(np.linspace(1,10,5)) #[1. 3.25 5.5 5.75 10.] döner 
print(np.linspace(1,20,5)) 
print(np.linspace(1,21,5))
print(np.linspace(1,21,10))
print(np.linspace(1,21,10,endpoint=True))
print(np.linspace(1,21,10,endpoint=False))
print(np.linspace(1,21,10,retstep=False))
print(np.linspace(1,21,10,retstep=True))

[ 1. 11.]
[ 1.    3.25  5.5   7.75 10.  ]
[ 1.    5.75 10.5  15.25 20.  ]
[ 1.  6. 11. 16. 21.]
[ 1.          3.22222222  5.44444444  7.66666667  9.88888889 12.11111111
 14.33333333 16.55555556 18.77777778 21.        ]
[ 1.          3.22222222  5.44444444  7.66666667  9.88888889 12.11111111
 14.33333333 16.55555556 18.77777778 21.        ]
[ 1.  3.  5.  7.  9. 11. 13. 15. 17. 19.]
[ 1.          3.22222222  5.44444444  7.66666667  9.88888889 12.11111111
 14.33333333 16.55555556 18.77777778 21.        ]
(array([ 1.        ,  3.22222222,  5.44444444,  7.66666667,  9.88888889,
       12.11111111, 14.33333333, 16.55555556, 18.77777778, 21.        ]), 2.2222222222222223)


In [46]:
#Indexing ve Slicing 

In [49]:
a=np.arange(10)
print(a)
print(slice(2,7,2))

[0 1 2 3 4 5 6 7 8 9]
slice(2, 7, 2)


In [51]:
#a[position]
#a[begin:end]
#a[begin:end:step]
#a[begin:end:step,begin:end:step]

In [61]:
a=np.arange(10)
print(a)
a[5]


[0 1 2 3 4 5 6 7 8 9]


5

In [62]:
a[2:6]

array([2, 3, 4, 5])

In [59]:
a=np.array(10)
print(a)


10


In [75]:
a=np.array(['DS','DA','ML','Python','R','AI'])
print(a)
a[1]
print(a[3:6])
print(a[:4])
print(a[1:5:2])
print(a[-1:-6:-2])
print(a[[0,3,4]])


['DS' 'DA' 'ML' 'Python' 'R' 'AI']
['Python' 'R' 'AI']
['DS' 'DA' 'ML' 'Python']
['DA' 'Python']
['AI' 'Python' 'DA']
['DS' 'Python' 'R']


In [76]:
a=np.array(['DS','DA','ML','Python','R','AI'])
print(a)
a.ndim

['DS' 'DA' 'ML' 'Python' 'R' 'AI']


1

In [78]:
a.shape

(6,)

In [83]:
print(a[0:3])
print(a[::2])
print(a[-1:-6:-2])
print(a[::-2])

['DS' 'DA' 'ML']
['DS' 'ML' 'R']
['AI' 'Python' 'DA']
['AI' 'Python' 'DA']


In [84]:
a=np.array([['DS','DA','ML','Python'],['R','AI','Weka','DM'],['C','Java','Dotnet','C#']])
print(a)
a.shape

[['DS' 'DA' 'ML' 'Python']
 ['R' 'AI' 'Weka' 'DM']
 ['C' 'Java' 'Dotnet' 'C#']]


(3, 4)

In [107]:
print(a[0,0])
#print(a[0][0])
print(a[0,])
print(a[0,0:4:1])
print(a[1:3,1:3])
print(a[0:3:2,0:4:3])
print(a[[0,2],[0,3]])
print(a[[0,2],])
print(a[(0,2),(0,3)])

DS
['DS' 'DA' 'ML' 'Python']
['DS' 'DA' 'ML' 'Python']
[['AI' 'Weka']
 ['Java' 'Dotnet']]
[['DS' 'Python']
 ['C' 'C#']]
['DS' 'C#']
[['DS' 'DA' 'ML' 'Python']
 ['C' 'Java' 'Dotnet' 'C#']]
['DS' 'C#']


In [108]:
a=np.array([1,2,3,4,5])
b=np.array([10,20,30,40,50])
print(a+b)

[11 22 33 44 55]


In [112]:
a=np.array([[1,2,3,4],[5,6,7,8]])
b=np.array([10,20,30,40])
print(a+b)
print(a.T)  #transpoze ettik

[[11 22 33 44]
 [15 26 37 48]]
[[1 5]
 [2 6]
 [3 7]
 [4 8]]


In [113]:
#Statistical Functions , Operators and Random Numbers

In [118]:
a=np.array([[1,2,3,4],[5,6,7,8]])
b=np.array([10,20,30,40])
print(a)
print(np.min(a))
print(np.max(a))
print(np.mean(a))
print(np.median(a))
print(np.std(a))

[[1 2 3 4]
 [5 6 7 8]]
1
8
4.5
4.5
2.29128784747792


In [120]:
#Arithmetic Operators

In [126]:
a=np.array([[1,2,3,4],[5,6,7,8]])
b=np.array([10,20,30,40])
print(a)
print(np.add(a,b))
print(np.subtract(a,b))
print(np.power(a,b))
print(np.power(b,2))
print(np.multiply(a,b))
print(np.divide(a,b))

[[1 2 3 4]
 [5 6 7 8]]
[[11 22 33 44]
 [15 26 37 48]]
[[ -9 -18 -27 -36]
 [ -5 -14 -23 -32]]
[[          1     1048576 -1010140999           0]
 [    9765625 -1190133760  1878557649           0]]
[ 100  400  900 1600]
[[ 10  40  90 160]
 [ 50 120 210 320]]
[[0.1        0.1        0.1        0.1       ]
 [0.5        0.3        0.23333333 0.2       ]]


In [127]:
#np.linalg komutu

In [130]:
a=np.array([[1,2],[3,4]])
b=np.array([[10,20],[30,40]])
print(a)
np.dot(a,b)
# 1 2     10 20
# 3 4     30 40
#1*10 + 2*30 = 70
#1*20 + 2*40 = 100
#3*10 + 4*30 = 150
#3*20 + 4*40 = 220

[[1 2]
 [3 4]]


array([[ 70, 100],
       [150, 220]])

In [134]:
a=np.array([[1,2],[3,4]])
b=np.array([[10,20],[30,40]])
np.matmul(a,b)
#matrix multiplication 

array([[ 70, 100],
       [150, 220]])

In [135]:
a=np.array([[1,2],[3,4]])
b=np.array([[11,12],[13,14]])
np.matmul(a,b)

array([[37, 40],
       [85, 92]])

In [137]:
a=np.array([[1,2],[3,4]])
b=np.array([[11,12],[13,14]])
print(a)
np.vdot(a,b)
# 1 2     11 12
# 3 4     13 14
#1*11 + 2*12  + 3*13 + 4*14  --> 130 

[[1 2]
 [3 4]]


130

In [139]:
a=np.array([[1,2],[3,4]])
b=np.array([[11,12],[13,14]])
print(a)
np.inner(a,b)
# 1 2     11 12
# 3 4     13 14
#1*11 + 2*12  --> 35
#1*13 + 2*14  --> 41 
#3*11 + 4*12  --> 81
#3*13 + 4*14  --> 95

[[1 2]
 [3 4]]


array([[35, 41],
       [81, 95]])

In [142]:
a=np.array([[1,2],[3,4]])
b=np.array([[11,12],[13,14]])
print(a)
np.linalg.det(a)
# 1 2     
# 3 4     
# 1*4 - 2*3 

[[1 2]
 [3 4]]


-2.0000000000000004

In [143]:
np.random.rand(2,2)

array([[0.30610779, 0.85094388],
       [0.15105222, 0.74710752]])

In [144]:
# rand randint random() choice RandomState seed() 