In [1]:
#https://www.udemy.com/course/numpy-with-python/learn/lecture/17677106?start=15#overview

#3 saat

#NumPy+with+Python+-+DATAhill+Solutions.pdf indirildi
#DATA+SCIENCE+with+DA,+ML,+DL,+AI+using+Python+&++R.pdf indirildi

#Anaconda kullanıyor



In [2]:
import numpy as np
print(np.__version__)



1.21.6


In [6]:
a=[1,2,3,4,5]
print(a)
type(a)  
# [1,2,3,4,5]
b=np.array(a)
print(b) #  [1 2 3 4 5]
print(b+100)

[1, 2, 3, 4, 5]
[1 2 3 4 5]
[101 102 103 104 105]


In [7]:
b.shape # 5 verir 5 eleman var içinde
b.dtype #(int32) verir

dtype('int32')

In [10]:
a= np.array([1,2,3,4,5,6,7,8,9,10],ndmin=2)
print(a) #-->  [[1 2 3 4 5 6 7 8 9 10]]  verir
a.shape #(1,10) verir
a.dtype #int32 verir

[[ 1  2  3  4  5  6  7  8  9 10]]


dtype('int32')

In [12]:
a= np.array([1,2,3,4,5,6,7,8,9,10],dtype=complex)
#dersek dtype complex123 gelir
#ayrıca yanına +0j eklenir
print(a)


[ 1.+0.j  2.+0.j  3.+0.j  4.+0.j  5.+0.j  6.+0.j  7.+0.j  8.+0.j  9.+0.j
 10.+0.j]


In [13]:
a= np.array([[1,2,3],[4,5,6]])
print(a) # [[1 2 3] [4 5 6]]
a.shape # (2,3) verir

[[1 2 3]
 [4 5 6]]


(2, 3)

In [15]:
a= np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(a)  
a.shape # (2,2,3) verir



[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


(2, 2, 3)

In [17]:
a= np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(a)  
a.shape # (4,3) verir


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


(4, 3)

In [18]:
a= np.array([[1,2,3],[4,5,6]])
print(a)  #[[1 2 3] [4 5 6]]
a.shape =(3,2) #verirsek
a.shape #(3,2) verir
print(a) #[[1 2] [3 4] [5 6]] verir



[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [20]:
#Numpy Array devam:

a= np.array([[1,2,3],[4,5,6]])
print(a) # [[1 2 3] [4 5 6]]
a.reshape(3,2)
#ama a'ya bunu eşitlemezsek işlemez a yine 2,3 olarak devam eder
a=a.reshape(3,2)
print(a)



[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [21]:
print(a.ndim) #  dersek 2 döner 2 boyut var.

2


In [23]:
a= np.array([1,2,3,4,5,6])
print(a)
a=a.reshape(3,2)
print(a) # [[1 2] [3 4] [5 6]]
print(a.ndim)  #2



[1 2 3 4 5 6]
[[1 2]
 [3 4]
 [5 6]]
2


In [26]:
#np.empty(shape, dtype=float,order='C')  c row-major demektir
#bir de F var o da column-major order demektir
np.empty([3,2])  # 3*2lik çok küçük tesadüfi sayılardan oluşan
#array oluşturur
np.empty([3,2],dtype=int)
#array([[1,2],[3,4],[5,6]])# verir



array([[1, 2],
       [3, 4],
       [5, 6]])

In [28]:
np.zeros([3,2],dtype=int)
#array([[0,0],[0,0],[0,0]]) verir



array([[0, 0],
       [0, 0],
       [0, 0]])

In [29]:
np.ones([3,2],dtype=int)
#array([[1,1],[1,1],[1,1]]) verir



array([[1, 1],
       [1, 1],
       [1, 1]])

In [31]:
a=[1,2,3,4,5]
print(a)
type(a) #  [1,2,3,4,5]
b=np.asarray(a,dtype=int)
print(b) #  [1 2 3 4 5]



[1, 2, 3, 4, 5]
[1 2 3 4 5]


In [32]:
#np.arange(start,end,step) kullanımı
np.arange(5) #dersek array([0,1,2,3,4]) verir
print(np.arange(5)) #dersek [0 1 2 3 4] verir
print(np.arange(5,dtype=float)) #[0. 1. 2. 3. 4.] verir
print(np.arange(1,11)) #[1 2 3 4 5 6 7 8 9 10] döner
print(np.arange(1,11,2)) #[1 3 5 7 9] döner



[0 1 2 3 4]
[0. 1. 2. 3. 4.]
[ 1  2  3  4  5  6  7  8  9 10]
[1 3 5 7 9]


In [33]:
#linspace() kullanımı
print(np.linspace(1,11,2)) # [1. 11.] döner 
print(np.linspace(1,10,5)) #[1. 3.25 5.5 5.75 10.] döner 



[ 1. 11.]
[ 1.    3.25  5.5   7.75 10.  ]
